### ISSUE TITLE
Left/start repeat sign/barline remains visible when you turn "Show barlines" off  

### ISSUE THREAD

**Issue by JoanEliot** [Jojo-Schmitz/MuseScore#109]
### Issue type

Other type of issue

### Bug description

I didn't test all the options, but with the _Show barlines_ box unchecked, only the left/start repeat sign remains visible — right/end repeat sign/barline and double barlines vanish, as do regular barlines. 

### Steps to reproduce

Right click a staff. 
Choose Staff/Part Properties
Uncheck "Show barlines"
Click OK or Apply.
Result: all barlines vanish from the staff, except the left/start repeat sign. 

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/30822817/236111840-5649f0f2-d228-4798-b464-32ea336f3a1e.png)

### MuseScore Version

OS: Windows 10 (10.0) or later, Arch.: x86_64, MuseScore version (32-bit): 3.7.0.4843924417, revision: github-musescore-musescore-51d07a

### Regression

I don't know

### Operating system

Windows 10 Pro

**Comment by Jojo-Schmitz** [comment]
Same issue in 3.x and before and still in 4.x.

So report this at https://github.com/musescore/MuseScore/issues/new/choose, and once it is fixed there I'll see whether I can backport the fix to 3.x.

This one might be due to the left/start repeat barline being special, see also #17429

**Comment by Jojo-Schmitz** [comment]
I guess I should make more clear what the purpose of this issue tracker here is: it is for reporting regressions vs. 3.6, for requesting backports of 4.x fixes that apply to 3.x too and for reporting issues that are unique to 3.x.

**Comment by JoanEliot** [comment]
Ok, understood. I wasn't aware that the main MS issue tracker is still active regarding 3.x, since 4 seems to be the thing. Thanks.

**Comment by Jojo-Schmitz** [comment]
See #17488
