### ISSUE TITLE
Mac builds for the 3.x branch are not done anymore on GitHub CI

### ISSUE THREAD

**Issue by Jojo-Schmitz** [Jojo-Schmitz/MuseScore#111]
### Issue type

Other type of issue

### Bug description

There have been warnings like this since quite a while on previous builds:

The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583

Seems now the time has finally come where it got disabled

### Steps to reproduce

1. Push a new commit to the 3.x branch
2. See that the GitHub action for Mac gets queued and sticks there forever

### MuseScore Version

3.7

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 10.15

**Comment by AntonioBL** [comment]
Maybe you can try the flag `-UseModernBuildSystem=NO` as suggested here:
https://stackoverflow.com/a/51205222
when using xcodebuild in the build step here:
https://github.com/Jojo-Schmitz/MuseScore/blob/3.x/Makefile.osx

Ciao,
ABL

**Comment by Jojo-Schmitz** [comment]
Thanks, let's try this

**Comment by Jojo-Schmitz** [comment]
That indeed fixed it!
