### ISSUE TITLE
Beam position does not change when Offset X is changed in inspector

### ISSUE THREAD

**Issue by yonah-ag** [Jojo-Schmitz/MuseScore#126]
### Issue type

UI bug

### Bug description

Note stems can be moved in both X and Y directions.
Note beams can only be moved in Y direction.
This is the case for guitar tablature scores.

### Steps to reproduce

1. Create any guitar tab score without linked notation.
2. Enter any notes which have beamed rhythm.
3. Select a beam and change Offset X in Inspector.

The beam does not move horizontally.

### MuseScore Version

3.6.2 & 3.7

### Regression

No.

### Operating system

Windows 10

**Comment by Jojo-Schmitz** [comment]
This does seem to work in 4.x, but there it IMHO is rather a bug, changeing a beams offsets moves the entire enchilada, notes stems, acvcidantals etc. along withthe beams.
In 3.x the beams change when the __chords__ change their offset, not when the notes ot stems do.
In 3.x I can't even chan ge a beam's y-offset, so I don't understand why you can?
It does follow stem lenght thoug, as it should

**Comment by yonah-ag** [comment]
What is the purpose of having an x-offset on beams that has no effect? Is it for MusicXML exports where other systems may implement it? MS4 certainly sounds like it is messing things up here.

**Comment by Jojo-Schmitz** [comment]
Guess you'd better bring this up against the upstream repo's master branch?
