### ISSUE TITLE
Windows, 64-bit: for some users Plugins don't work at all

### ISSUE THREAD

**Issue by Jojo-Schmitz** [Jojo-Schmitz/MuseScore#128]
### Issue type

Other type of issue

### Bug description

Plugins using QtQuick (`import QtQuick 2.2` or the like, like almost all plugins do) fail to load in the 64-bit version for Windows (which uses Qt 5.15.2) for some users (not for me though)

### Steps to reproduce

1. Open plugin manager
2. See it not showing any plugin to activate

OR

1. Open plugin creator
2. File > New
3. Run
4. Running…
Creating component failed
line 1: plugin cannot be loaded for module "QtQuick": Cannot load library (PathToInstallDir)\MuseScore-3.7.0.(BuildNumber)-x86_64\qml\QtQuick.2\qtquick2plugin.dll: the specified module could not be found.
5. Check in Explorer: that dll does exist at that place

### MuseScore Version

3.7

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows

### Additional context

See https://musescore.org/en/node/342126#comment-1172480 ff. and https://musescore.org/en/node/351021

With the 32-bit version of MuseScore (which uses Qt 5.9.9) plugins work.
64-bit Windows can run 32-bit applications.

**Comment by Johan-v** [comment]
Any hope this will get fixed?

**Comment by Jojo-Schmitz** [comment]
I don't like the idea to have the 64bit Windows version also to fall back to Qt 5.9, and haven't yet found the real reason for the issue.

**Comment by Jojo-Schmitz** [comment]
But using the 32bit version seems an easy workaround

**Comment by Johan-v** [comment]
Hello,
From time to time I try it again.
But if the pluginsettings from 64bit do also change the settings in 32 bit.
So if the plugins are broken in 64bit they are also lost in 32bit.

Any possibility to separate 64bit and 32bit?

Kind regards,

Op za 1 jul 2023 om 09:30 schreef Joachim Schmitz ***@***.***

**Comment by Jojo-Schmitz** [comment]
Sorry, I don't get that. Yes, if you have the 32-bit version __and__ the 64-bit version, they do share their settings and no, it is not possible to separate that, but you'd really need only one.
Anyway, even with having both, this should not have any influence on the Plugins, other that the same plugin works in 32-bit but doesn't in 64-bit

**Comment by Johan-v** [comment]
This is a bit difficult to explain. 

I have many plugins in the plugin folder
But not all are ticked in the pluginmanager
Everything is fine in 32 bit.

Now loading 64bit
Start the pluginmanager
The plugins are also ticked in the 64bit pluginmanager but they are nog available.
There is a button reload plugsins in the pluginmanager
If I tick that in the 64bit pluginmanager the plugins become unticked.

When I start 32bit version after doing that the plugins are also inticked in 32 bit.

Where is the config file for the ticked plugins for the pluginmanager stored in windows?
Maybe I can first save a copy before messing in 64bit.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, it is whether a plugin is enabled or not.
But as far as I'm aware for those users where plugins in the 64-bit version don't work, none of them works, so no need to tamper with the settings to reload or enable them.

The settings file is %LOCALAPPDATA%/MuseScore3development/plugins.xml

**Comment by Johan-v** [comment]
Now I see.
The 64bit version does delete all entries in plugins.xml after the reload plugins button has been ticked.

**Comment by Jojo-Schmitz** [comment]
Don't do this then 😉

**Comment by Jojo-Schmitz** [comment]
See also #140, I believe it has the same underlying cause.

**Comment by Jojo-Schmitz** [comment]
I might have nailed it, see #149

**Comment by Jojo-Schmitz** [comment]
Fixed via #149
