### ISSUE TITLE
Chords over triplets disappear when time signature is changed or measures joined

### ISSUE THREAD

**Issue by BanjoJake** [Jojo-Schmitz/MuseScore#132]
### Issue type

Other type of issue

### Bug description

Chords and staff text attached to the triplets are lost if time signature is changed or measures are joined.

[Time Sig Change Bug.zip](https://github.com/Jojo-Schmitz/MuseScore/files/11894841/Time.Sig.Change.Bug.zip)

### Steps to reproduce

(1)   In the attached file, drag 4/4 time signature over the existing 2/4 time signature;  the Cm chords and staff text attached to the triplets disappear.

(2)  In the attached file, join measures 6 and 7 (leaving the existing 2/4 time signature unchanged).   The Cm chords and staff text attached to the triplets disappear.

### MuseScore Version

3.7.0.5389870991, revision: github-musescore-musescore-5ac2a85

### Regression

No.

### Operating system

Windows 10

### Additional context

I reported this issue first in v3.6.2 (github.com/musescore/MuseScore/issues/15090).  It is fixed in v4.1 (beta)

**Comment by Jojo-Schmitz** [comment]
Note to.sepf: backporting #15129 should do the trick.

**Comment by Jojo-Schmitz** [comment]
Check #133

**Comment by BanjoJake** [comment]
Fixed !  
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 3.7.0.5422089050, revision: github-musescore-musescore-18bb4ae
THANK YOU !!!
Jake

**Comment by BanjoJake** [comment]
Fixed !  
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 3.7.0.5422089050, revision: github-musescore-musescore-18bb4ae
THANK YOU !!!
Jake
