### ISSUE TITLE
Some Command-line Arguments do not work in version 3.7

### ISSUE THREAD

**Issue by BanjoJake** [Jojo-Schmitz/MuseScore#143]
### Issue type

Other type of issue

### Bug description

This works (exports PDF) in v3.6.2 and v4.1:
"C:\Program Files\MuseScore 3\bin\MuseScore3.exe" -o Hora.pdf Hora.mscx
However it doesn't work using v3.7, neither 64 nor 32 bit.

Some command-line options do work in 3.7, eg, -h and -v
verified the bug using mscz. 

### Steps to reproduce

Open a Windows command window, copy a mscx file into the active directory.  Delete any PDF files in the active directory.  then enter 
"C:\Apps\MuseScore-3.7.0\bin\MuseScore3.exe" -o Hora.pdf Hora.mscx
  (using the actual installed folder of course)
Look for PDF files in the active directory (confirm there are none)

### MuseScore Version

3.7.0.5740844078 / ca2865a

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11 and 10

**Comment by Jojo-Schmitz** [comment]
Seems the bug got introduced when the -u command line option got added for 'unroll repeats'

**Comment by Jojo-Schmitz** [comment]
Real easy fix (basically a typo or rather copy/past fail), for a bug that is exactly 1 year old now ;-)
Thanks for bringing it to my attention!

**Comment by Jojo-Schmitz** [comment]
Fixed via #144

**Comment by BanjoJake** [comment]
Confirmed both 32-bit and 64-bit working in latest version; THANK YOU !
