### ISSUE TITLE
Windows, 32 & 64-bit Header and Footer Texts misplaced

### ISSUE THREAD

**Issue by HeinzVo** [Jojo-Schmitz/MuseScore#150]
### Issue type

UI bug

### Bug description

In the latest artifact "3.7.0.5784330917-x86_64" the Plugins and Palettes bugs [#128,#140] seams to be resolved, many thanks, but:

The Header and Footer Texts are now misplaced (not placed with the correct distance from page in X and Y directions - all texts overlap, see screenshots below.

### Steps to reproduce

Open attached score in ZIP and switch Header/Footer on and off (Format / Style / Header, Footer), see screenshots.
a) All the texts overlap at the left side of the page!
b) Switching on/off the Header-Text unexpectedly shifts down the hole score, causing unnecessary page breaks!
[Detected Problems MuseScore-3.7.X.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12279964/Detected.Problems.MuseScore-3.7.X.zip)

### Screenshots/Screen recordings

![MuseScore 3 7 0 5784330917-x86_64_Header-Footer misplaced(1)](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/b094264d-4c36-4d40-91ae-cb62efb1ccff)
![MuseScore 3 7 0 5784330917-x86_64_Header-Footer misplaced(2)](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/091da754-2721-4083-b018-1b4f20833e29)
![MuseScore 3 6 2_Header-Footer (placing ok)(1)](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/96f0a732-ed36-4fbb-be17-43bfdf5002cd)

### MuseScore Version

3.7.0 (any windows version)

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10, 64-bit

**Comment by Jojo-Schmitz** [comment]
Hmm, might be a(n undesired) side effect or #146 to fix #145?

**Comment by Jojo-Schmitz** [comment]
b) still happening

**Comment by Jojo-Schmitz** [comment]
That looks like a regression vs. 3.6.2, but really is by design, for the header not to 'bleed' into the title frame / top musical margin, see https://github.com/musescore/MuseScore/issues/9043 and https://github.com/musescore/MuseScore/issues/9043

**Comment by Jojo-Schmitz** [comment]
Reg. b) see #19014 (for master)
