### ISSUE TITLE
Suggestion: quick little update of Plugin Creator code

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#154]
### Your idea

I just updated the Chord Level Selector plugin and found that I had to make changes multiple times to the .qml file with an external editor and then re-test it for moving some elements around and got perturbed that I had to press the "Reload" button and then press Run over and over again, instead of just Run as a keyboard shortcut.

I present a quick change that you can choose to implement if you'd like or not, but I see no reason not:

`mscore/plugin/pluginCreator.cpp`
merely add load();

```cpp
 void PluginCreator::runClicked()
       {
+      load();
       log->clear();
       msg(tr("Running…\n"));
```
This will do what I wanted, with the only problem that if you edit code in the editor itself, you'd want to make sure to save before running (which I think you'd do anyways)

Additionally, I gave the Run and Stop buttons the ampersands so `Alt+R` and `Alt+S` would work as keyboard shortcuts:

------------------------ mscore/plugin/pluginCreator.ui ------------------------
index 9a7c342fd5..ccd93a4171 100644
@@ -43,26 +43,26 @@
```cpp
           <sizepolicy hsizetype="Expanding" vsizetype="Fixed">
            <horstretch>0</horstretch>
            <verstretch>0</verstretch>
           </sizepolicy>
          </property>
          <property name="text">
-          <string>Run</string>
+          <string>&amp;Run</string>
```
```cpp
         <widget class="QPushButton" name="stop">
          <property name="sizePolicy">
           <sizepolicy hsizetype="Expanding" vsizetype="Fixed">
            <horstretch>0</horstretch>
            <verstretch>0</verstretch>
           </sizepolicy>
          </property>
          <property name="text">
-          <string>Stop</string>
+          <string>&amp;Stop</string>
          </property>
         </widget>
        </item>
```

### Problem to be solved

After saving externally, merely press Alt+R and it will run the updated plugin if you keep your plugin-creator open. Less clicking around.

**Comment by Jojo-Schmitz** [comment]
Good idea, but...

* I'd rather automagically save() before, or warn that unsaved changes will be lost.
* I'm not sure changing translatable strings are a good idea without having a translation infrastructure in place

**Comment by worldwideweary** [comment]
Yeah, makes sense not to include into your branch for others.

For me personally, the use case is for an *external* editor to do the coding, and the Plugin-Manager to be used for running the changes of the plugin really quickly by merely pressing Alt-R in the manager instead of having to 1) mouse click 'reload' icon and 2) mouse click 'run', so it would be self-defeating to re-save the code from MuseScore's editor because that would overwrite once again the code saved from the external editor. I hate the editor provided in the manager, so its only use case is to get console output and to facilitate testing instead of having to "reload plugins" from within musescore and clicking around

Maybe not for others, but for your own purposes if you ever do some plug-in editing in external editor, I suggest to try it out.

**Comment by Jojo-Schmitz** [comment]
How about saving it only if it got changed in the Plugin Editor itself?

**Comment by worldwideweary** [comment]
Oh, that'd make sense. Wonder if there's a method marking the file as *changed*

**Comment by worldwideweary** [comment]
Taken care of with conversations + manual merge after #155 +  #156

**Comment by Jojo-Schmitz** [comment]
Ah, seems I had forgotten to close this

**Comment by worldwideweary** [comment]
:) P.S. nice to see possible backwards compatibility with MS4 files. Hope it works out.

**Comment by Jojo-Schmitz** [comment]
Feel free to test it
