### ISSUE TITLE
Trills and Short Trills - Import from MS4 failed

### ISSUE THREAD

**Issue by HeinzVo** [Jojo-Schmitz/MuseScore#177]
### Issue type

File corruption

### Bug description

Introduction:
-------------
Importing MS4.x scores to Mu3.7 is a very interesting feature, but at that early implementation state
a) a load error message pops up and must be clicked away
b) many elements and some styles go lost during import
c) the page layout gets corrupt due to erroneous rescaled element positions and spacer/gap-distances (should be 1=1)
   NOTE - page layout corruption problems are already reported here:
   https://github.com/Jojo-Schmitz/MuseScore/issues/165
   https://github.com/Jojo-Schmitz/MuseScore/issues/141
   https://github.com/musescore/MuseScore/issues/19014

Due to the corrupted page layout in MS3.7, it is difficult to reference to a page or a point in the attached score-examples, where a problem has detected.
First referencing the section/frame number in the score and then referencing a measure number in that section may identify the place (or just watch the screenshots).

New Reports, import from MS4 failes [->]:
-----------------------------------------
-  MuseScore 3.7.0_Staff Texts Style Expression - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measure 159]
-  MuseScore 3.7.0_Crescendo Hairpins - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measure 155]
-  MuseScore 3.7.0_Ornaments Short Trills - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measures 134,142,148,151]
=> MuseScore 3.7.0_Ornaments Trills - Import from MS4 failed  [Gloria in D-major, Section 10, Measures 120,130]
-  and probably many other elements not yet tested ...

-  MuseScore 3.7.0_Crescendo Lines - Import from MS4 incomplete (Lines style wrong and not visible)  [Gloria in D-major, Section 12, Measures 76-77]
-  MuseScore 3.7.0_Text Lines - Import from MS4 incomplete (Lines style wrong and not visible)  [Gloria in D-major, Section 12, Measures 76-77]
-  MuseScore 3.7.0_Elements Style Dynamic - Import from MS4 incomplete (text style and size wrong)  [Missa brevis in G-major, Section 6, Measures 131,139,143,153,157]
-  and probably some other styles not yet tested ...

Other Reports, corrupting the page layout [https://github.com/Jojo-Schmitz/MuseScore/issues/165],[https://github.com/Jojo-Schmitz/MuseScore/issues/141]:
-----------------------------------------
-  MuseScore 3.7.0_Elements Offset - Import from MS4 corrupted (numbers changed)  [Missa brevis in G-major, Section 6, Measure 131]
-  MuseScore 3.7.0_Spacers and frame top¦bottom gaps - Import from MS4 corrupted (numbers changed)  [Gloria in D-major, Section 12, Measures 68/71,71/75]
-  MuseScore 3.7.0_Not hiding staff with subsequent empty measures after crescendo line in measure before  [Gloria in D-major, Section 10, Measures 1-8]

### Steps to reproduce

Steps to reproduce:
-------------------
1.) take a MS3.6.2-score and import it to MS4.x; save it there
2.) take that MS4.x-score and import it back to MS3.7

NOTE: check attached testscores and screenshots

### Screenshots/Screen recordings

![MuseScore 3 6 2_Ornaments Trills](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/5a6d0542-5707-4244-824f-ff2b1d5e5ad8)
![MuseScore 3 7 0_Ornaments Trills - Import from MS4 failed](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/437c7e28-53a2-4295-9a55-8c8f327a9688)

### MuseScore Version

MuseScore-3.7.0.6145742308-x86_64

### Regression

No.

### Operating system

Windows10 and 11, 64-bit

### Additional context

[Mu3.7 import from Mu4.x failed, incomplete or corrupt.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12683872/Mu3.7.import.from.Mu4.x.failed.incomplete.or.corrupt.zip)

**Comment by Jojo-Schmitz** [comment]
See #182

**Comment by Jojo-Schmitz** [comment]
Resolved with #182
