### ISSUE TITLE
Elements Style Dynamic - Import from MS4 incomplete (text style and size wrong)

### ISSUE THREAD

**Issue by HeinzVo** [Jojo-Schmitz/MuseScore#180]
### Issue type

File corruption

### Bug description

Introduction:
-------------
Importing MS4.x scores to Mu3.7 is a very interesting feature, but at that early implementation state
a) a load error message pops up and must be clicked away
b) many elements and some styles go lost during import
c) the page layout gets corrupt due to erroneous rescaled element positions and spacer/gap-distances (should be 1=1)
   NOTE - page layout corruption problems are already reported here:
   https://github.com/Jojo-Schmitz/MuseScore/issues/165
   https://github.com/Jojo-Schmitz/MuseScore/issues/141
   https://github.com/musescore/MuseScore/issues/19014

Due to the corrupted page layout in MS3.7, it is difficult to reference to a page or a point in the attached score-examples, where a problem has detected.
First referencing the section/frame number in the score and then referencing a measure number in that section may identify the place (or just watch the screenshots).

New Reports, import from MS4 failes [->]:
-----------------------------------------
-  MuseScore 3.7.0_Staff Texts Style Expression - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measure 159]
-  MuseScore 3.7.0_Crescendo Hairpins - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measure 155]
-  MuseScore 3.7.0_Ornaments Short Trills - Import from MS4 failed  [Missa brevis in G-major, Section 6, Measures 134,142,148,151]
-  MuseScore 3.7.0_Ornaments Trills - Import from MS4 failed  [Gloria in D-major, Section 10, Measures 120,130]
-  and probably many other elements not yet tested ...

-  MuseScore 3.7.0_Crescendo Lines - Import from MS4 incomplete (Lines style wrong and not visible)  [Gloria in D-major, Section 12, Measures 76-77]
-  MuseScore 3.7.0_Text Lines - Import from MS4 incomplete (Lines style wrong and not visible)  [Gloria in D-major, Section 12, Measures 76-77]
=> MuseScore 3.7.0_Elements Style Dynamic - Import from MS4 incomplete (text style and size wrong)  [Missa brevis in G-major, Section 6, Measures 131,139,143,153,157]
-  and probably some other styles not yet tested ...

Other Reports, corrupting the page layout [https://github.com/Jojo-Schmitz/MuseScore/issues/165],[https://github.com/Jojo-Schmitz/MuseScore/issues/141]:
-----------------------------------------
-  MuseScore 3.7.0_Elements Offset - Import from MS4 corrupted (numbers changed)  [Missa brevis in G-major, Section 6, Measure 131]
-  MuseScore 3.7.0_Spacers and frame top¦bottom gaps - Import from MS4 corrupted (numbers changed)  [Gloria in D-major, Section 12, Measures 68/71,71/75]
-  MuseScore 3.7.0_Not hiding staff with subsequent empty measures after crescendo line in measure before  [Gloria in D-major, Section 10, Measures 1-8]

### Steps to reproduce

Steps to reproduce:
-------------------
1.) take a MS3.6.2-score and import it to MS4.x; save it there
2.) take that MS4.x-score and import it back to MS3.7

NOTE: check attached testscores and screenshots

### Screenshots/Screen recordings

![MuseScore 3 6 2_Elements Style Dynamic](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/cb151dd7-197a-4329-a1d8-84167b6551ca)
![MUB408~1](https://github.com/Jojo-Schmitz/MuseScore/assets/140117374/0c22e425-92ea-4f9b-8e60-fb5e87cc4fe0)

### MuseScore Version

MuseScore-3.7.0.6145742308-x86_64

### Regression

No.

### Operating system

Windows10 and 11, 64-bit

### Additional context

[Mu3.7 import from Mu4.x failed, incomplete or corrupt.zip](https://github.com/Jojo-Schmitz/MuseScore/files/12683933/Mu3.7.import.from.Mu4.x.failed.incomplete.or.corrupt.zip)

**Comment by Jojo-Schmitz** [comment]
The corresponding style settings from Mu4 seem to not exist in Mu3, from the debug output:
```
Debug: line 537 col 26: dynamicsOverrideFont (C:\Users\Jojo\Documents\GitHub\MuseScore\libmscore\xmlreader.cpp:211, void Ms::XmlReader::unknown())
Debug: line 538 col 18: dynamicsFont (C:\Users\Jojo\Documents\GitHub\MuseScore\libmscore\xmlreader.cpp:211, void Ms::XmlReader::unknown())
Debug: line 539 col 18: dynamicsSize (C:\Users\Jojo\Documents\GitHub\MuseScore\libmscore\xmlreader.cpp:211, void Ms::XmlReader::unknown())
```
Seems the matching style settings are `dynamicsFontFace` and `dynamicsFontSize`, no counterpart for `dynamicsOverrideFont` though.

Seems an easy fix...

**Comment by Jojo-Schmitz** [comment]
Please report it there

**Comment by Jojo-Schmitz** [comment]
Actually those values do not have any counterpart, `dynamicsOverrideFont` is a bool (whether or not to use an override font), dynamicsFont` is that override font and `dynamicsSize` is a percentatage, not a font size.

So neither a bug here nor easy to fix or backport :-(

**Comment by Jojo-Schmitz** [comment]
The lack of importing those settings in Mu4 seems a bug though, so, again, please report it there

**Comment by Jojo-Schmitz** [comment]
The Mu3 style settings `dynamicsFontSize` and `dynamicsFontFace` simply get lost on Mu3 score import into Mu4

**Comment by Jojo-Schmitz** [comment]
You've just reported itstream, see #19633
