### ISSUE TITLE
Hooks should be drawn as square cap 

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#190]
### Issue type

Engraving bug

### Bug description

And not flat cap. It's possible simply changing 
```cpp
pen.setCapStyle(Qt::FlatCap);
```
to 
```cpp
pen.setCapStyle(Qt::SquareCap); 
```
will do the trick for when drawing hooks

@ libmscore/textlinebase.cpp
@line 117 on 3.x branch at the moment. 

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/07a079f3-2d50-4e7a-9923-4bc27f899411)

![](https://user-images.githubusercontent.com/7139517/270592641-cd3aff60-87f6-4cd1-8538-ec8f4a63511b.png)

Think it was a left over change from transitioning when right before switching to polyline for hairpins because it used to overlap way too much and look like hexagons

### Steps to reproduce

.

### MuseScore Version

3.x

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

.

**Comment by worldwideweary** [comment]
P.S. hope all is well over there

**Comment by Jojo-Schmitz** [comment]
All fine, thanks hope all is well for you too.

square caps might look better for 90° hooks, but not for 45° ones (which too look bad with flat caps):
flat caps:
![image](https://github.com/Jojo-Schmitz/MuseScore/assets/1786669/0afc418d-af57-47ae-ab6a-1327cb9bb37b)
square caps:
![image](https://github.com/Jojo-Schmitz/MuseScore/assets/1786669/aae85221-9352-4116-b932-67458184f740)
maybe round caps?:
![image](https://github.com/Jojo-Schmitz/MuseScore/assets/1786669/f8091896-63bb-450d-8a8a-bda26f4645df)

Or draw them as polylines, just like for hairpins?

**Comment by Jojo-Schmitz** [comment]
See #191

**Comment by Jojo-Schmitz** [comment]
@worldwideweary , comments?

**Comment by worldwideweary** [comment]
P.S. How do you get that amber color highlight of  @ user name? It looks nice

**Comment by Jojo-Schmitz** [comment]
What amber color? Looks black and bold to me

**Comment by worldwideweary** [comment]
![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/9ad104d8-c572-4a7d-83f2-d3a0a0b46365)

Tis what it looks like over here. Maybe it's a theme thing...

**Comment by Jojo-Schmitz** [comment]
Ah, dark mode, it seems

**Comment by Jojo-Schmitz** [comment]
Those polyline pedal lines should be donw in Mu4 too/first

**Comment by Jojo-Schmitz** [comment]
If and once done in Mu4, I'll backport polylines ;-)
