### ISSUE TITLE
Reading Mu4.2+ scores with 3.7 doesn't work

### ISSUE THREAD

**Issue by Johan-v** [Jojo-Schmitz/MuseScore#252]
I have problems reading portable nightly MS4 files in 3.7
Is it still possible?

Kind regards

**Comment by Jojo-Schmitz** [comment]
Sample score? (ZIPed)

**Comment by Johan-v** [comment]
[V4 Trumpets for Christmas.zip](https://github.com/Jojo-Schmitz/MuseScore/files/13636129/V4.Trumpets.for.Christmas.zip)

**Comment by Jojo-Schmitz** [comment]
That score is not from the Beta, but from a development version, from the master branch, a150a9b
It should work anyhow, but I can cofrim that it does not.
Need to investigate...

**Comment by Jojo-Schmitz** [comment]
Culprit found, there's a new tag ```<LastEID>53851</LastEID>``` that Mu3.7 apparently doesn't like

**Comment by Johan-v** [comment]
Indeed from development version. Sorry.

**Comment by Jojo-Schmitz** [comment]
See #253

**Comment by Johan-v** [comment]
Working confirmed. Top!

**Comment by Jojo-Schmitz** [comment]
Fixed via #253
