### ISSUE TITLE
Interfacing with musescore.com crashes program

### ISSUE THREAD

**Issue by AuraDJ** [Jojo-Schmitz/MuseScore#261]
### Issue type

Crash or freeze

### Bug description

After the dialogue, that appears after uploading a score to musescore.com or when trying to log in, opens, the software crashes after ~1 second.
It works without problems with 3.6.2 and 4.2

### Steps to reproduce

1. Click on save online
2. When logged out: crashes after the log in dialogue appears
3. Wait until the score is uploaded
4. Crashes after score property dialogue opens up

### MuseScore Version

3.7

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

My locale is set to Japanese despite the rest of my system being in German. (Just listing it here in case it only crashes for me and this might be the reason.)

**Comment by Jojo-Schmitz** [comment]
I can't reproduce. I also can't set to Japanese (as I won't find my way back)...

**Comment by Jojo-Schmitz** [comment]
Actually I can, with the GitHub artifacts, but not with my own local build

**Comment by ErlingIv** [comment]
Same happens to me,  on both windows 10 & 11

**Comment by Jojo-Schmitz** [comment]
Is this the same with the 32bit build and the 64bit build?

**Comment by Jojo-Schmitz** [comment]
The 64buit build crashes deep inside Qt5WenEnficeCore.dll.
Major differens to the 32but build (which doesn't crash here) is the Qt version used, 5.12.2 vs. 5.9.9
The upload apparently does work though!

**Comment by FuckTankies** [comment]
I also encountered a similar problem. A few hours ago, I could upload the music scores generated by evolution 64 bit version on win11 platform to the MS website. When I tried to upload the same music scores again in the evening, I found that I could not upload them. It prompts"Error: wrong format, Please choose MSCZ file."
![图片](https://github.com/user-attachments/assets/efa0ebda-8507-4bcf-b20c-e32c4c5f5aec)

**Comment by Jojo-Schmitz** [comment]
Tried using Save online from within MuseScore 3.7?

**Comment by FuckTankies** [comment]
![图片](https://github.com/user-attachments/assets/9d3ce2a7-3c4b-4485-9416-064fefee1434)


> Tried using Save online from within MuseScore 3.7?

Internal Server Error occured

**Comment by FuckTankies** [comment]
> Tried using Save online from within MuseScore 3.7?

Can I upload my MSCZ file here to find the reason for the issue?

**Comment by Jojo-Schmitz** [comment]
Sure, zip it first

**Comment by FuckTankies** [comment]
> Sure, zip it first

It's OK now. It seems that MS website has some radical changes recently.

**Comment by Jojo-Schmitz** [comment]
It seems the crash is related to QtWebEngineProcess.exe from Qt 5.15.2, if that gets replaced by the one from Qt 5.9.9, there's no crash anymore (when using "Save online")
Bit instead the same empty dislog is shown as with 3.6.2.
In any case the score does get uploaded though.

Another possible fix might be to somehow (?) build 3.7 without QtWebEngine support, just like in my local MinGW build (QtWebEngine is only supported with and available for MSVC), in that case the 'regular' system browser (on Windows it should be Edge) should appear

**Comment by Jojo-Schmitz** [comment]
See also https://musescore.com/groups/improving-musescore-com/discuss/5266069

**Comment by ErlingIv** [comment]
64bit version works fine on Windows 10. No crash. Thank you!

**Comment by Jojo-Schmitz** [comment]
Looks like an incompatible OpenSSL version, I don't think I can fix this, seems you'd have to get and install a matching OpenSSL version

**Comment by Jojo-Schmitz** [comment]
Did the old webengin version work on Linux?

**Comment by zorba77** [comment]
>
>
> Did the old webengin version work on Linux?
>
> How can activate it?
The self compiled software returns this error:
[image: image.png]

**Comment by Jojo-Schmitz** [comment]
By downloading an older artifact

**Comment by zorba77** [comment]
It didn't work

Il giorno ven 13 dic 2024 alle ore 15:10 Joachim Schmitz <
***@***.***> ha scritto:

**Comment by Jojo-Schmitz** [comment]
But with a different error, right?
