### ISSUE TITLE
Some properties of slurs and volta's are lost after vertical blocks are removed.

### ISSUE THREAD

**Issue by Serg-SVM** [Jojo-Schmitz/MuseScore#267]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

In some cases, when removing horizontal or text blocks, some elements (such as slur and volta) lose some properties. The problem is present in versions 3.6.2, 3.7 and 4.2

### Steps to reproduce

1. Open the example [test.zip](https://github.com/Jojo-Schmitz/MuseScore/files/13841007/test.zip)
2. Delete the block labeled "Delete me"
3. The Slur loses the adjustment of its position, Volta resets the "Automatic placement" property

### Screenshots/Screen recordings

![Shot_2024-01-05_13-29-58](https://github.com/Jojo-Schmitz/MuseScore/assets/155729679/e11d1ebe-3c1f-45c3-a600-bfd401efaf2b)
![Shot_2024-01-05_13-30-20](https://github.com/Jojo-Schmitz/MuseScore/assets/155729679/22543209-59e6-44d2-8b0f-e91069557977)

### MuseScore Version

3.6.2

### Regression

No

### Operating system

Linux (Debian 12)

**Comment by Jojo-Schmitz** [comment]
Please report (also) on https://github.com/musescore/MuseScore/issues/new/choose

**Comment by Jojo-Schmitz** [comment]
I took your code from https://github.com/musescore/MuseScore/issues/20841#issuecomment-1883077483 to turn it into PR 270

**Comment by Jojo-Schmitz** [comment]
Please tell me your (GitHub) email adress, so I can credit you for the code change

**Comment by Jojo-Schmitz** [comment]
Closed via #270
