### ISSUE TITLE
Update Readme for 3.7

### ISSUE THREAD

**Issue by trlkly** [Jojo-Schmitz/MuseScore#283]
### Your idea

I'm very happy you are continuing to backport fixes to Musescore 3. However, it is currently really complicate to figure out how to download this Musescore 3.7 Evolution.

It would be nice if you'd modify the Readme file to include instructions on how to download the already compiled files. I did it once, and I wish to update, but I cannot find it. 

### Problem to be solved

It would make it easier for anyone who wants to continue using Musescore 3.

Also, it would make it easier to test and see if the latest version has a problem, so you don't report a bug that has already been fixed.

**Comment by trlkly** [comment]
I did figure it out after clicking around in various places, but it was complicated. I had to go to Actions, expand the column on the left, click the **second** CL_Windows, click the most recent fix (Fix GH#18187), and then scroll down to find the artifacts, choosing the correct one for my architecture (in my case, 64-bit). 

It would be nice to have a link that took you at least to the list of fixes, then told you to click on the latest fix and then scroll down to the artifacts.

**Comment by Jojo-Schmitz** [comment]
Check https://sites.google.com/view/musescore-3-evolution/ for instructions

Change the readm would either not help much (like when applied to ther 3.x branch only, as that's requite the user to switch to that branch first) or destroy my ability to work on the master branch to help with the upstream repo, as it'd cause merge conflicts on every single PR.
Not sure how to get out of this.

**Comment by Jojo-Schmitz** [comment]
OK, foind a way and fixed this in a7e7821

**Comment by Jojo-Schmitz** [comment]
Even has the added benefit of making it easier to create PRs against 3.x (and I won't accept PRs against master anyway, as those need to go upstream).
