### ISSUE TITLE
The Plugin UI reacts too slowly to user interactions

### ISSUE THREAD

**Issue by lgvr123** [Jojo-Schmitz/MuseScore#298]
The time taken by the UI of plugin to react to button click is slow.

This observable with the plugin [TapTempo](https://github.com/lgvr123/musescore-taptempo/blob/ResponsivenessIssue/taptempo/taptempo.qml).

When clicking the "Tap" button at 120bpm (withe the help of an external metronome), in MU3.6.2, the UI reacts fast enough and the plugin is able to compute the 120bpm.

In MU3.7 (and idem in MU4.2.1), the UI is not able to react fast enough for computing such BPMs. There is a limit at +-115bpm. This corresponds to a delay of 0.5" between events. The UI is not able to handle events with <0.5s between them.

### Demo in MU3.7
![tempoMU37](https://github.com/Jojo-Schmitz/MuseScore/assets/50494/48c74f6f-1080-49af-9b56-86b2e0e8da95)

One can see that the plugin misses a few clicks

### Demo in MU3.6.2
![tempoMU36](https://github.com/Jojo-Schmitz/MuseScore/assets/50494/4f34fd98-adc0-4e96-9470-a955eed5a653)

One can see that the plugin handles all the clicks

**Comment by Jojo-Schmitz** [comment]
Same with the Window 43-bit build? And the Linux AppImage? If so that lfeels like a Qt version issue, 5.9.9 vs. 5.15.2

**Comment by lgvr123** [comment]
Per this [StackOverflow discussion](https://stackoverflow.com/questions/67908324/qml-faster-button-clicking) I changed on the `onClicked` by a `onReleased` which responses faster than the `onClicked`. This solution solves the responsiveness issue in both MU3.7, MU4.x.

I guess this is an acceptable solution and that this issue can be closed.

**Comment by Jojo-Schmitz** [comment]
OK, let's put it to a rest then
