### ISSUE TITLE
Remember audio driver

### ISSUE THREAD

**Issue by Johan-v** [Jojo-Schmitz/MuseScore#300]
I have multiple audio drivers on my laptop.
ASIO 
Wasapi 
etc.

MU3.7 does not always remember or use my prefered setting.
I use multiple audio apps simulaneously. (reaper, VLC, XMplay, MU3, MU4)
I would like MU evolution to always use Wasapi.
Any config file for this?

Kind regards,

**Comment by Jojo-Schmitz** [comment]
None that I'd know of, and if, it'd be the same as in 3.6.2 and earlier
