### ISSUE TITLE
Moving an element changes the modification time to a date (v3.7)

### ISSUE THREAD

**Issue by BanjoJake** [Jojo-Schmitz/MuseScore#340]
In the attached file, move the subtitle or a chord, and the time stamp (below left) changes into a date stamp. Saving the file corrects it.   I agree that it's not that serious, the only issue is if I print before I save, and fail to notice, then the double date gets 'frozen' in.  My main concern is that moving one chord sometimes unintentionally changes the position of others, but that effect is more elusive, so I'm hoping that fixing the time/date bug also fixes the chords jumping around. 

Windows 11, MuseScore version (64-bit): 3.7.0.7968364542,  
Windows 10  MuseScore version (64-bit): 3.7.0.8014604524.

Comments from Forum (musescore.org/en/node/360851#comment-1230017)
[Jojo-Schmitz ...][Feb 21, 2024 - 06:10]
... seems a bug in 3.7 and 3.7 only, doesn't seem to happen in 3.6.2 nor 4.2.1 and a problem with the $m marco.

[Chord Move Changes Time to Date.zip](https://github.com/Jojo-Schmitz/MuseScore/files/14386318/Chord.Move.Changes.Time.to.Date.zip)

**Comment by BanjoJake** [comment]
Confirmed doesn't happen in 4.2.1 nor 3.6.2

**Comment by worldwideweary** [comment]
This is caused by #8555, not by the backporting of it so far as I can see. 

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/2b0a6f78-d282-461c-802d-b4a74640329e)

**Comment by Jojo-Schmitz** [comment]
So Mu4 has the same issue?

**Comment by worldwideweary** [comment]
> So Mu4 has the same issue?

Wtf Jojo, looks like you did this back in 2022, but did it for Mu4 only:
https://github.com/musescore/MuseScore/pull/13107

**Comment by Jojo-Schmitz** [comment]
Oh boy, Alzheimer's...

**Comment by worldwideweary** [comment]
God help us
