### ISSUE TITLE
Button "Rewind to beginning"

### ISSUE THREAD

**Issue by Rabadman** [Jojo-Schmitz/MuseScore#445]
When the "Rewind to beginning" button is pressed, the view of the sheet of music no longer jumps to the beginning.

If you then press the Play button, the music is played from the beginning but the sheet of music is not tracked.

Jumping to the beginning is only possible with the "Pos1" button

Similar behavior exists in MS 4.x and is now also executed in MS 3.7

Is this behavior intentional?

**Comment by Jojo-Schmitz** [comment]
No, it isn't, as far as I can tell.
Mind to report that against 4.0 too?

**Comment by zorba77** [comment]
I can confirm the issue in MS 3.7, I haven't tried in 4.X

OS: Ubuntu 22.04.4 LTS, Arch.: x86_64, MuseScore version (64-bit): 3.7.0.8678350200, revision: GitHub-Jojo-Schmitz-MuseScore-acbfac0

**Comment by Rabadman** [comment]
The behavior of MS 4.2.1 and MS 4.3 currently differs from MS 3.7 as follows.

The same behavior when pressing the "Rewind to beginning" button.
However, if you then press the Play button, playback starts from the beginning and the note image starts from the beginning.

I can report this for MS 4, but I am not sure whether this is not intended for MS 4.

Tested on Windows 11 Home, 23H2
MS 4.2.1 (64 bit)
MS 4.3.0 (MuseScore-Studio-Nightly-241170504) 64 bit

I hope the text is understandable, as I use an online translator from German to English.

**Comment by worldwideweary** [comment]
@Jojo-Schmitz can you confirm this? Pressing rewind "jumps" to the beginning fine for me on latest builds here.

**Comment by Jojo-Schmitz** [comment]
Not for me, so yes, I can confirm

**Comment by worldwideweary** [comment]
For me this is what happens (Goes to beginning) Maybe I'm misinterpreting the conversation, or it's contingent upon some sort of setting.... This is from recent build downloaded today:


https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/ef2a787f-2d37-408a-a096-a23ac5e3b00c

**Comment by Jojo-Schmitz** [comment]
Take a multi page score, play on page 3, then press that button

**Comment by worldwideweary** [comment]
Ok. Same behavior:

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/4a80792e-15f9-49fc-80f2-58d0a3c92ec0

**Comment by Jojo-Schmitz** [comment]
Maybe only if the Navigator is active?

**Comment by worldwideweary** [comment]
Oh come on, "Three strikes and you're out" as they say in America

https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/c1e71174-de3f-4227-9d8b-45dab2cd3d62

**Comment by Jojo-Schmitz** [comment]
Well, what can I say, this is what should happen, and does on 3.6.2, but does not in the current (selfbuild MinGW) 3.7 on my machine (Windows 11)

**Comment by worldwideweary** [comment]
Yeah, I'm using vertical pages. Looks like the problem only "rears its ugly head" in "horizontal" mode!

**Comment by Jojo-Schmitz** [comment]
Because that button moves up, but not left

**Comment by worldwideweary** [comment]
Ok. With that in mind, I confirm that the culprit is more than likely my #377. Fix one thing, break another. I'll hopefully fix it within the next few days
