### ISSUE TITLE
Importing MU4 scores looses all style settings

### ISSUE THREAD

**Issue by Jojo-Schmitz** [Jojo-Schmitz/MuseScore#447]
The style settings are read, from score_style.css, but apparently not taken into effect

Results in e.g. Jazz-style scores to loose their style, but also score in concert pitch to loose that setting
Esp. the latter is a quite critical problem.

**Comment by zorba77** [comment]
Is it possible to open 4.X mscz score with MS 3.7?
When I try it tells me that the file was saved with a newer version of MS

**Comment by Jojo-Schmitz** [comment]
Yes it is, just ignore that message

**Comment by Jojo-Schmitz** [comment]
@worldwideweary mind to take a look at this? I'm looking at that sonce months and don't see where it is going wrong

**Comment by Jojo-Schmitz** [comment]
I think I used `e.skipCurrentElement()` only for those style settings I want to skip and not log as unknown?

**Comment by worldwideweary** [comment]
Just linked to the PR

**Comment by worldwideweary** [comment]
> I don't want to see them showing up as errors in the debug output, so I skip them

Haven't been getting any errors in the debug output for incompatibility, but check the PR and the build or build a debug version and test it out and see there are some issues

**Comment by Jojo-Schmitz** [comment]
In code like this:
```cpp
            else if (isMu4 && tag == "lyricsDashLineThickness") { // 0.1 -> 0.15
                  qreal lyricsDashLineThickness = e.readDouble();
                  if (qFuzzyCompare(lyricsDashLineThickness, 0.1)) // 4.x default, let's skip, i.e. reset back
                        e.skipCurrentElement();
                  else
                        set(Sid::lyricsDashLineThickness, Spatium(lyricsDashLineThickness));
 ```
I want to "est" the style setting for the default to take over

**Comment by Jojo-Schmitz** [comment]
Ah, I guess I see now, I read it already, so "ate" it, and then `skipCurrentElement`whould actualy skips the __next__ element, bad thinko...

**Comment by worldwideweary** [comment]
Yeah it some how "pulls out entirely" after one of the "eatings" ... so it seemed like there was no further XML reading afterwards. Stopped at for instance **lyricsDashLineThickness**
