### ISSUE TITLE
MuseScore crash  when copying from stave 1 to stave 2 in a piano score

### ISSUE THREAD

**Issue by ErlingIv** [Jojo-Schmitz/MuseScore#472]
Crash in V3.6 and 3.7, but not in 4.3 when copying notes between staves. ( see https://musescore.org/en/node/363800 )

**Comment by Jojo-Schmitz** [comment]
[Crash-copy-staff-1-to-staff-2.zip](https://github.com/Jojo-Schmitz/MuseScore/files/15250009/Crash-copy-staff-1-to-staff-2.zip)

**Comment by worldwideweary** [comment]
Just checked it out, and noticed MS is crashing at the actualTicks() call for the tuple pasting. Will look at it later, but if look into it it's around:

```cpp
Score::pasteStaff() function - 
    if (tuplet->rtick() + tuplet->actualTicks() > measure->ticks();
```

You could cheat and just use "ticks()" but that might have bad consequences...
