### ISSUE TITLE
Combined PDF export is faulty

### ISSUE THREAD

**Issue by K-Hilde** [Jojo-Schmitz/MuseScore#487]
When exporting to a PDF file with the options 
- Combined into a single file
- Export with background present in score, **or**
- Export with custom background color

then the content in the generated PDF is invisible. It only works with the setting "Export with transparent background". 

![Export](https://github.com/Jojo-Schmitz/MuseScore/assets/143805366/fe9cad83-857a-4cdd-b956-80e275d33534)

As the generated PDF files of all three variants (transparent, present in score, custom color) have approximately the same size, it can be assumed that the content is present but is hidden by the background color. This is also shown by the variant with the 'custom background color' if the alpha channel of the color is set to a value less than 127. 
Assumption: the background color layer is at the top. 
The error does not occur if the option "As a separate file" is selected. 

Both background options are new in MuS 3.7. These options are not available in 3.6.2.

**Comment by K-Hilde** [comment]
I have to add the version: 
OS: Windows 7 SP 1 (6.1), Arch.: x86_64, MuseScore version (32-bit): 3.7.0.9065998290, revision: GitHub-Jojo-Schmitz-MuseScore-490db99

**Comment by Jojo-Schmitz** [comment]
Strange, I can only partly reproduce: it creates an empty (well, that background) **last** page of main score and each part, but all non-last pages are visible

**Comment by Jojo-Schmitz** [comment]
Or were your attempts single page scores and parts?

**Comment by K-Hilde** [comment]
Yes, it was just a demo score with a single page. 

And indeed, if I take a longer score, only the last page will have the background color or custom color applied. All other pages are (probably) created with a transparent background - like with the third option. Example with yellow background, alpha=127:
[Example-Score_and_Parts_alpha_127.pdf](https://github.com/Jojo-Schmitz/MuseScore/files/15442484/Example-Score_and_Parts_alpha_127.pdf)
Only the last page gets the background color and while alpha is less than 255 you can see the notes. 
Non-last pages seems to use the transparent background.

**Comment by Jojo-Schmitz** [comment]
That doesn't make it easier at all ;-(

**Comment by Jojo-Schmitz** [comment]
Mu4 doesn't have these options apparently, came in via (a port of) #7500

**Comment by worldwideweary** [comment]
In passing, it looks like the dimensions are not correct either, but I don't know if that's how it's "designed" to be or not. That is, for example in 3.7 in app with a custom dimension: 

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/0c1877ca-d3cf-41b4-af28-501657e9a818)


Yet exported with the combined into single file (first page):

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/0bdca277-93f6-44f8-add0-dfe3817f5d8c)


Might/Probably be a separate but related issue

**Comment by worldwideweary** [comment]
Same thing with the previous problem... custom settings were getting overwritten by the ::id function it seemed like. I'll put together a PR for testing purposes and you can take it from there
