### ISSUE TITLE
The export to PDF is not correct when using custom page sizes

### ISSUE THREAD

**Issue by Amnordeos** [Jojo-Schmitz/MuseScore#491]
The result of an export to PDF is always in A4 format, the format set in "Page Options" is not respected, therefore if the format is larger it is cut off.

PDF export is correct in versions 3.6.2 and 4.3.0 with the same score.

**Comment by Amnordeos** [comment]
PDF export is correct in versions 3.6.2 and 4.3.0 with the same score.

**Comment by Jojo-Schmitz** [comment]
U can't reproduce, changing an existing score from A4 to A3 exports it as an A3 PDF

**Comment by Amnordeos** [comment]
Export to PDF works fine with items in the "Page Dimensions" list except when it is a "custom" dimension.

MuseScore Rev. 7fb03fa

**Comment by worldwideweary** [comment]
P.S. while visiting this repository today, I just double checked a build from like early april / late march and it seemed to not have this problem with a custom pdf... if that's of any help. I probably won't look into it further at the moment

**Comment by worldwideweary** [comment]
Looks like #475 is the culprit.
Not 100% certain, but I'd guess that the following code-change block is the problem:

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/65e12fe0-c9a4-409a-b72b-8fec21adbd6e)

If it is (you should try reverting this commit and see the results)... i'm not sure what the appropriate thing is to do. Apparently "setpapersize" is made obsolete. Maybe this isn't the problem specifically, but this commit seems to be.

**Comment by Jojo-Schmitz** [comment]
As usual spot on, thanks! Will check there.

**Comment by Jojo-Schmitz** [comment]
None of the `setPageSize()` combinations I tried worked, so I've reverted it to `setPaperSize()`

**Comment by Jojo-Schmitz** [comment]
Could be a bug in Qt, fixed in a later version

**Comment by worldwideweary** [comment]
Hrm... try this if you don't mind:

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/679ddcc7-1374-42ec-a88d-a3c1abae2f4b)

+      QPageSize ps(size, QPageSize::Inch);

I.e., use the constructor that just takes size and units without using the ::id() function. It appears to be working ok for me here after testing. It might be worth it.

**Comment by Jojo-Schmitz** [comment]
But isn't that a bit besides the point of that id() method, which is to use a well known format whenever possible?

**Comment by worldwideweary** [comment]
Aren't the Sid::pageWidth&Height definitions already in conformity with the well known formats got from page properties options? If not,... then yeah never mind I suppose.

**Comment by worldwideweary** [comment]
Either way, whatever works ;)

**Comment by worldwideweary** [comment]
P.S. 

![image](https://github.com/Jojo-Schmitz/MuseScore/assets/7139517/8f9ef48f-b3f6-4a38-8270-6c8d7c8664f6)

... the default fuzzy matching applies still to the QPageSize constructor, which is the flag to attempt to match into a known paper size if it's within something like 3 units... so the ::id() function is non-necessary it seems to me with the non-obsolete function
