### ISSUE TITLE
French/Didactic tablature headless 64th rhythm

### ISSUE THREAD

**Issue by RickyChitarrone** [Jojo-Schmitz/MuseScore#547]
The tablature note value 64th note (hemidemisemiquaver) for French Baroque (headless) isn't working. Whether I type "1" in my keypad or click the 64th note icon in the palette, I get a dot rather than a flag when entering tablature in Didactic. 

<img width="144" alt="Untitled 2" src="https://github.com/user-attachments/assets/86f4470e-883f-432d-84bc-2885acfc17aa">

A search with the term "musescore tablature headless 64th" revealed a 2018 report of this, which appears in the issues section of the MuseScore site. [Link here](https://musescore.org/en/comment/1250930#comment-1250930) 

If I must use a symbol because Evolution doesn't have the flag, where do I find the headless French tablature rhythm flags, as shown in the screenshot above? I was able to find symbols for headless flags in conventional notation as stand-in, but obviously they are a mismatch for the look of my project. Thanks!

Richard
OS: macOS 13.3, Arch.: x86_64
MuseScore version (64-bit): 3.7.0.9232793350, revision: GitHub-Jojo-Schmitz-MuseScore-b756ccd

**Comment by RickyChitarrone** [comment]
Hi Jojo. Somebody else will need to answer whether the issue reaches forward to 4.x.x. I stopped using current MuseScore because of various instabilities triggered by lute tablatures. Cadiz might know. He was very helpful to me early on and pointed me to Evolution.

**Comment by worldwideweary** [comment]
@RickyChitarrone the source code directories of musescore carry the font being used for tablature notation, including headless french

MuseScore/fonts/mscoreTab.ttf

If you're set on doing so, you could probably install that font into your system, then find the appropriate symbols and insert them as special characters in a staff text and manually set their sizes. Might be worth the effort depending on the necessity of your situation. That's supposing that 64th flags for that particular font style actually exist in the font, about which I'm not certain - it very may well be the case that the font designers didn't get that far. Good luck!

**Comment by worldwideweary** [comment]
While I'm up, here's a screenshot of FontForge contents:

![image](https://github.com/user-attachments/assets/f6d03b6c-4e95-4ab2-a768-81c3c6df0fcb)

**Comment by RickyChitarrone** [comment]
That image answers the question: the font designer never got that far. The next slot is in the font map is occupied by the very placeholder dot that I see in my tablature. Maybe they figured baroque lutes would never play at that level of diminution?

Do you think it’s possible to knock on that designer’s door, figuratively speaking, and ask nicely for an update? I’d be happy to send him a thank-you gift out of appreciation. There are a few other aspects of the font that could also be improved for legibility purposes too. I’ve never done font design before (I’m a performer with end-user chops only when it comes to computers), but if someone would tell me what to read / where to look to get started, I’d be pleased to try my hand at it.

**Comment by worldwideweary** [comment]
You can try FontForge: https://fontforge.org/en-US/ and some guide like with http://designwithfontforge.com/en-US/index.html

You could try to add another "flag" and scale, but splines are kind of crazy to work with from my experience. 

Here's my attempt at winging a 64th fairly quickly as an example:
![image](https://github.com/user-attachments/assets/143e14ff-7c96-4f0c-b993-d65d8d5e8850)

You can attempt to email the guy. It appears to have been added by:
Maurizio M. Gavioli <mmg@vistamaresoft.com>  back in 2015 or so.

If you try your hand at it, if it'd be of any use, here's the font with the symbol I put in there. It's not great, but you could maybe work with it or just copy and paste the 32nd and try your hand at it in font forge after reading about it:

[mscoreTab.ttf.zip](https://github.com/user-attachments/files/16397286/mscoreTab.ttf.zip)

You'd have to recompile musescore for it to work natively... or add it manually if not via staff text

**Comment by RickyChitarrone** [comment]
Hey Jojo, that glyph is super. I’d happily use that as is! 

I don’t know what it means to recompile a program, but it sounds like something that would come with a warning, “don’t try this at home, kids.”

I will start by writing to Maurizio. It’s his handwork and he deserves first refusal (= _Recht der ersten Ablehnung_; _Vorkaufsrecht_) at updating it. I think what he did is brilliant and need to tell him so, regardless. 

However this happens, once there’s a finalized, revised font, would it be possible to fold it into a release of MS and Evolution’s newer builds? Otherwise I’ll need to find out about decompiling / recompiling, which is above my musician’s pay level.

**Comment by worldwideweary** [comment]
I can try later to do a pull request against the font file to see if you can try the artifact and make sure to test there aren't other side-effects. I'm not very good with font creation, so who knows. I'll see what I can do. P.S. Check the icon - this is not @Jojo-Schmitz  ;-)

**Comment by RickyChitarrone** [comment]
JESSE! My bad. Sorry about that. It’s the way my mail headers show on my phone. No excuse for not paying closer attention, but there you have it!

**Comment by worldwideweary** [comment]
It's all good Ricky (Well, maybe not *all* good, someone said somewhere sometime that only "Someone" is good, but that's a different story at hand here). To be fair, if you're using e-mail it's more limiting of course.

Here you go though: check #548 once the artifacts are finished building and see if it works... I haven't tested it yet

**Comment by Jojo-Schmitz** [comment]
Closed via #548
