### ISSUE TITLE
v3.7 Removing a measure crashes MU

### ISSUE THREAD

**Issue by youtsos** [Jojo-Schmitz/MuseScore#550]
OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 3.7.0.10173931325, revision: GitHub-Jojo-Schmitz-MuseScore-ec9f91b

Remove Selected Range for measure 82 crashes MU.
The same for measure 81+82 works fine. 
See attached img.

**Pls lmk how to upload/attach  .mscz score file**

![Remove measure bug](https://github.com/user-attachments/assets/efa1154f-5bfa-41fe-ad05-a09471eb74c0)

**Comment by Jojo-Schmitz** [comment]
Zip it and attach that

**Comment by youtsos** [comment]
Thx!

[MEDLEY_3.zip](https://github.com/user-attachments/files/16446850/MEDLEY_3.zip)

**Comment by Jojo-Schmitz** [comment]
Will look into it after vacation

**Comment by worldwideweary** [comment]
@Jojo-Schmitz Looks like it's probably due to #106 somehow

**Comment by Jojo-Schmitz** [comment]
So a duplicate of #414, and fixed by #419?

**Comment by worldwideweary** [comment]
I hadn't checked, but I just tried a very recent build (3.7.0.10333009461, revision: GitHub-Jojo-Schmitz-MuseScore-eaf8a8a) 

and couldn't crash 3.7 by way of [measure delete] or time-signature replacement for the 1/4 time signatured measure, but can in an older personal build....so it seems this is a non-issue. I'm not sure how to quickly see the "date" associated with the revision numbers (is there a quick way?) since the OP mentioned ec9f91b

**Comment by Jojo-Schmitz** [comment]
That one is 16 day old, just before my vacation, but there hasn't happened too much since then

**Comment by worldwideweary** [comment]
"That" being eaf8a8a I suppose. Wondering how old is 3.7.0.10173931325, ec9f91b? There should be a way to test that quickly some how you'd think

**Comment by worldwideweary** [comment]
#2773 doesn't have the problem either... which seems older than the OP's revision number.

**Comment by Jojo-Schmitz** [comment]
No, that is 4h old

**Comment by zorba77** [comment]
With the latest version MS 3.7 crash removing the first bar. Not for every score, but very often.
One time I removed the first bar and all went fine, but it crash when I tried to undo with CTRL+z

**Comment by Jojo-Schmitz** [comment]
So indeed a duplicate of #414, and fixed by #419, can you try the atrifacts from that? I'll rebase now, so you'd get a fresh one

**Comment by zorba77** [comment]
I just delete and undo the first measure in 7 orchestral scores without crashes on linux

**Comment by Jojo-Schmitz** [comment]
Closed as a duplicate of #414
