### ISSUE TITLE
 Electric Guitar (treble clef) incorrectly transposes when linking to a TAB staff #23873 

### ISSUE THREAD

**Issue by mkj42** [Jojo-Schmitz/MuseScore#552]
3.7 Evo also has this problem.

With the instruments
Acoustic Guitar (treble clef)
and
Guitar (treble clef)
if you link a TAB staff, it behaves correctly as expected.

If, however, you try to link a TAB staff to Electic Guitar (treble clef),
the TAB is incorrect (transposed one octave too high).

Update:
I successfully modified the electric guitar (treble clef) section in the instruments.xml file.
using the other two for comparison

    I updated the string data (+12 on each of the six entries)
    I verified correct clef, transposing clef, diatonic and chromatic transpose entries (all were correct)

Important:
I then added my instruments.xml location to Musescore Edit/Preferences/Score Instrument list 2.

This issue can indeed be easily fixed by changing the included instruments.xml.

[electric guitar tab error.zip](https://github.com/user-attachments/files/16470375/electric.guitar.tab.error.zip)
![electric guitar tab error](https://github.com/user-attachments/assets/db0bdd84-23c9-4649-92da-acc965a0f16b)

**Comment by mkj42** [comment]
Good question
Probably is, does that change things here?
I stopped using and uninstalled 3.6.2 once I discovered 3.7.

**Comment by Jojo-Schmitz** [comment]
I'll investigate, once back from vacation

**Comment by mkj42** [comment]
Update: 
I tried modifying the electric guitar (treble clef) section in the instruments.xml file.
using the other two for comparison
* I updated the string data (+12 on each of the six entries)
* I verified correct clef, transposing clef, diatonic and chromatic transpose entries (all were correct)

Still no change
Under staff/part properties, the string data still shows as E2-E4, rather than the correct E3-E5 of the others.
Did I miss something?

**Comment by Jojo-Schmitz** [comment]
If you'dsend me your email address, I'd attribute the fix to you

**Comment by mkj42** [comment]
Sure, thanks
I sent you a message on musescore.org; please let me know if you get it.
I don't know how to contact you or whether to put my email on github?

By the way, I also expanded the treble clef instrument to have the same extra channels as the non-treble clef one.
Is that worth a separate feature request or not?
Thanks

**Comment by Jojo-Schmitz** [comment]
Yes, I got it
And yes, I'd like that change too, preferably in the same PR or even commit, I'll add it.

**Comment by mkj42** [comment]
Working fine here
Thanks so much
