### ISSUE TITLE
Add to measure number not working

### ISSUE THREAD

**Issue by zorba77** [Jojo-Schmitz/MuseScore#556]
Step to reproduce on every score:
- right click on a measure (the first or every measure of the score)
- Increase the "add to measure number" of an arbitrary value
- nothing happens, measure numbers, shown for example in every new system, is not increased.

In MS 3.6.2 it works.
If I open the score with MS 3.6.2, change the value, close the score and then reopen with MS 3.7 measure numbers are increased  correctly.

EDIT: with MS 3.7 it works if I:
- open the score
- change the value (nothing happens)
- close the score
- reopen the score
Now measure number is increased correctly.
So it seems that the value is loaded when you open a file, and saved, but is not changed in the open score while working

**Comment by Jojo-Schmitz** [comment]
So it is 'just' a temporary glitch, right?

**Comment by zorba77** [comment]
I don't know. 
To change the measure number I have to set it, save the file and reopen it.

**Comment by Jojo-Schmitz** [comment]
So yes, a temporary glitch

**Comment by worldwideweary** [comment]
Reminds me of that time MS4 got an update to make efficiency gains but had some issues with measure numbers dealing with section breaks. Probably related.
