### ISSUE TITLE
MS 3.7 prints too many pages

### ISSUE THREAD

**Issue by zorba77** [Jojo-Schmitz/MuseScore#587]
On Ubuntu 22.04 if I print a single copy of a part all is ok. 
But if I print multiple copies of a part (maybe also the score?) MS 3.7 print more copies than required.
If I want 2 copies it prints 4 pages.
With 3.6.2 I hadn't problems

**Comment by Jojo-Schmitz** [comment]
Somehow, somewhere, that does ring a bell, in the very far distance...

**Comment by Jojo-Schmitz** [comment]
Isn't it #15861 ?

**Comment by zorba77** [comment]
It's possible, the more I print the more come out

**Comment by Jojo-Schmitz** [comment]
Try the artifacts from #588, once they ae available

**Comment by zorba77** [comment]
No... I printed 3 copies but I got 9 pages... and I lost all settings, Ms opened the first settings dialog

**Comment by Jojo-Schmitz** [comment]
OK, back to the drawing board then...

**Comment by Jojo-Schmitz** [comment]
1st: I can confirm the issue
2nd: it indeed is a regression vs. 3.6.2
3rd: I wonder whether it is related to the Qt version used, 5.12.2 vs. 5.9. We could check by trying out a Linux or the Windows 32-bit artifact (not the ones from this PR though), as both are using the older Qt
4th: done then and non that version is affected too...
5th: so up into the debugger...

**Comment by Jojo-Schmitz** [comment]
6th: in debuger the changed code (!, i.e. this PR) behaves as extected
7th: it does so outside of the debugger too, so I'm fairly certain that this PR fixes the issue, please test again

**Comment by Jojo-Schmitz** [comment]
It may (now/still) be an issue with Qt versions, I just noticed that you're using Linux.
For Windows 64-bit and macOS it should be fixed now, both use Qt 5.12.2.
Not sure how (or whether) to fix it for Qt 5.9, i.e. for Linux and Windows 32-bit though.

**Comment by Jojo-Schmitz** [comment]
Then your earlier test was wrong, as I didn't change anything to the PR, I guess you didn't test the PR's artifact, but just the 3.x one at the time.
And now, as the PR is merged, too.

**Comment by zorba77** [comment]
??? Tomorrow I will do some tests
