### ISSUE TITLE
MS 3.7 doesn't export PDF in landscape format

### ISSUE THREAD

**Issue by zorba77** [Jojo-Schmitz/MuseScore#601]
MS 3.7 exports all pdf in portrait format, even if the score is set in landscape format. the consequence is that the pdf is cut on the right. I attached a score with 2 pdf for A4 and A5.
The same happens with the parts.
This is a very problematic bug, since the PDF export is essential to create parts to share.

[PDF.zip](https://github.com/user-attachments/files/16799919/PDF.zip)

**Comment by Jojo-Schmitz** [comment]
Confirmed :-(

**Comment by Jojo-Schmitz** [comment]
May relate to #16617

**Comment by zorba77** [comment]
> May relate to [musescore#16617](https://github.com/musescore/MuseScore/issues/16617)

I don't know, I don't tried to print a landscape score, I only created a PDF. SVG and PNG export are ok.
My OS is Linux.

**Comment by Jojo-Schmitz** [comment]
There's this code in all PDF exporting functions:
```cpp
      printer.setPageOrientation(size.width() > size.height() ? QPageLayout::Landscape : QPageLayout::Portrait);
```

**Comment by Jojo-Schmitz** [comment]
Deleting those seems to fix the issue, I just don't understand why

**Comment by Jojo-Schmitz** [comment]
Hmm, https://doc.qt.io/qt-6/qpagedpaintdevice.html#setPageOrientation says:

You should call this before calling [QPainter::begin](https://doc.qt.io/qt-6/qpainter.html#begin)(), or immediately before calling [newPage](https://doc.qt.io/qt-6/qpagedpaintdevice.html#newPage)() to apply the new orientation to a new page. You should not call any painting methods between a call to setPageOrientation() and [newPage](https://doc.qt.io/qt-6/qpagedpaintdevice.html#newPage)() as the wrong paint metrics may be used.

**Comment by zorba77** [comment]
I can confirm that the issue is closed for a single page score in landscape. 
The error remains exporting multipage scores or score with parts. In these situations only the first page is set in landscape (if needed).
I attached an old score, but this is true also for all my scores.
[20_inno tedesco.zip](https://github.com/user-attachments/files/16817806/20_inno.tedesco.zip)

**Comment by Jojo-Schmitz** [comment]
Darn... I had sort of anticipated that, so I made sure that this setting is done directly before all `pageNew()` calls.

**Comment by zorba77** [comment]
I'm reading the last commit,
 `                  if (!firstPage) {
                  printer.setPageOrientation(size.width() > size.height() ? QPageLayout::Landscape : QPageLayout::Portrait);
                  printer.newPage();
                  }`
       
Maybe is this the problem? The problematic code was removed only for the first page.

**Comment by Jojo-Schmitz** [comment]
I followed the Qt documentation above _You should call this ..., or immediately before calling [newPage](https://doc.qt.io/qt-5/qpagedpaintdevice.html#newPage)()_

**Comment by Jojo-Schmitz** [comment]
It seems a problem only with score (portrait) with parts (landscape) in one singe file, right?

**Comment by Jojo-Schmitz** [comment]
Mind to check the artifacts from #600

**Comment by Jojo-Schmitz** [comment]
* Printing seems not affected at all, so that change to `void MuseScore::printFile()` could get reverted, if it ain't broke, don't fix it....
* Exporting a single score (1 or more pages, all with the same orientation of course) could apparently get fixed by just removing that `setPageOrientation()` from `bool MuseScore::savePdf(Score* cs_, QPrinter& printer)`!
* Exporting score and parts as multiple files is basically the same case as abobe and works fine without that `setPageOrientation()`  being removed from that `bool MuseScore::savePdf(Score* cs_, QPrinter& printer)` too.
* Exporting Score and parts in a single file apparently works fine too with those 2 `setPageOrientation()` calls in `bool MuseScore::savePdf(QList<Score*> cs_, const QString& saveName)` being removed.

**Comment by Jojo-Schmitz** [comment]
We'd needs someone on Mac to test this too, these `savePDF()` methods do have some platform-dependant code in them

**Comment by Jojo-Schmitz** [comment]
Please test, I've force-pushed it to the 3.x branch

**Comment by zorba77** [comment]
Tests exporting PDF combined in a single file:
- export Landscape score and landscape parts: OK
- export portrait score and landscape parts: OK
- export landscape parts: OK
- export landscape score: OK
- export portrait score and mixed parts (landscape and portrait): OK
- export mixed parts: OK

-export portrait score and mixed parts in separated files: OK
-export landscape score and mixed parts in separated files: OK

Today I will do some experiments with printer

**Comment by Jojo-Schmitz** [comment]
All on Linux that is, right?

**Comment by zorba77** [comment]
> All on Linux that is, right?

Yes, KUbuntu LTS 22.04

**Comment by Jojo-Schmitz** [comment]
Fixed for Linix and Windows, let's close and reopen if Mac still has an issue

**Comment by zorba77** [comment]
I can confirm that a landscape score is printed rightly under linux
