### ISSUE TITLE
Enhancement: Note-entry -  move to previous chord

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#604]
Keyboard user observation: 

1. Note Entry - Switch to voice two when there isn't a voice two rest but there is in the previous measure
2. User can't move left to select voice-2 rests. Probably "by design" but I don't like it:
3. Option: User can use Prev-Element (alt-left) to do so but can't do so in note entry so exit note entry, alt-left a few times, then 
4. Back to note entry again. Either that. or move to the left measure and switch voices and then move forward to the designated area:

[Navigation.webm](https://github.com/user-attachments/assets/d9faf1da-ed24-4136-babf-00c307922922)

Seems kinda lame and imo would be better to allow this:

https://github.com/user-attachments/assets/7dbdc55b-2a8c-4160-80d4-7dd7bcadf84f

**Comment by Jojo-Schmitz** [comment]
Is this a regression vs 3.6? Or something that works better in Mu4?

**Comment by worldwideweary** [comment]
Neither, it's just an improvement for note entry in "3.7". trying to make sense of some of my older personal build changes because there's like 200+ commits with many bound up for multiple purposes. This would be one of the little ones

**Comment by Jojo-Schmitz** [comment]
So you plan for a PR on this?

**Comment by worldwideweary** [comment]
Yeah I'll try it out actually right now and you can test it out sometime later or whatever

**Comment by worldwideweary** [comment]
Oh, found a problem/regression  with #605 because it uses `nextChordRest(track, true);` which doesn't consider grace notes. Grace notes are then skipped while in note entry mode using "Previous chord" :-/

Have a fix....
Found the problem when realizing that likewise you can't be in "Voice-2" with no CR and then use "Previous Measure" command... doesn't do anything (it's always been that way in 3.6.2 etc). I'll get a PR to also allow that and fix the problem 
 a little later
