### ISSUE TITLE
Enhancement: Allow Q/W to perform duration toggle on a list selection

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#608]
#328 Updated so that the selection would retain the chords if the user has a list selection and performs duration changes by way of the pad toggle. Similar to Double/Half like a range selection, but inserts rests in-between the notes when making smaller form

I figured why not in addition let Q/W (with or without shift) do the same thing with the duration changes. That is
1. Range based Half/Double exists already (no rests result)
2. Do the recent up/down chord thing to convert to list and perform a delete, selection retained
3. Now perform Q/W on the list... with Shift/W showing. 
 
[qwList.webm](https://github.com/user-attachments/assets/abe88358-b625-4ea4-9326-1d703f384a51)

I don't see why not? Can do a PR

**Comment by Jojo-Schmitz** [comment]
Sure, go ahead

**Comment by worldwideweary** [comment]
Aside: came across a bug that can happen when increasing/decreasing as a list: if increased beyond, and then attempt to decrease again... something weird happens. This is how it is currently. Don't feel like fixing that, but the point is that same behavior will be even easier to happen by pressing Q/W I'd imagine:

[incdecbug.webm](https://github.com/user-attachments/assets/206a61ec-ce19-4be1-b879-df934c749c8e)

**Comment by worldwideweary** [comment]
Aside: came across a bug that can happen when increasing/decreasing as a list: if increased beyond, and then attempt to decrease again... something weird happens and a loss of the non-selected notes occurs (turned into rests). This is how it is currently. Don';t really feel like pursuing it, but the point is that same behavior would be even easier to happen by pressing Q/W quickly I'd imagine:

[incdecbug.webm](https://github.com/user-attachments/assets/206a61ec-ce19-4be1-b879-df934c749c8e)
