### ISSUE TITLE
I cannot turn multimeasure rests on or off

### ISSUE THREAD

**Issue by zorba77** [Jojo-Schmitz/MuseScore#616]
Today I noticed that I cannot turn multimeasure rests on or off with the usual "M" shortcut. Neither with MS 3.6 or 3.7.
I don't know why. Some days ago when I run an artifacts, it resetted all my settings, maybe this shortcut is broken?

**Comment by Jojo-Schmitz** [comment]
Works for me, check your shortcuts.xml

**Comment by Jojo-Schmitz** [comment]
```xml
  <SC>
    <key>toggle-mmrest</key>
    <seq>M</seq>
    </SC>
 ```

**Comment by Jojo-Schmitz** [comment]
That's the new default for Mu4. I had forgotten that I barckported that in #465
