### ISSUE TITLE
Musescore 3.7 does not run on Windows 7 nor in Windows 11

### ISSUE THREAD

**Issue by marianobelaunde** [Jojo-Schmitz/MuseScore#620]
I attempted to run a recent binary release of Musescore 3.7 in two windows machines: one is a windows 7 x86_64 machine and the other is windows 11 - also 64 bits) with no succees.
The exe file when executed in a cmd terminal does nothing at all - no warning no error printed, no GUI launched - just returns.

This is the command I launched (with the exact nightly version in folder name);
MuseScoreNightly-202408190421-3.x-972dbe2-x86_64\bin\MuseScore3.exe

Notice that if I pass --version option then I get a dialog box with version name "Musescore-3.7.0-Development".
Also if I pass --help I get a long list of option in a dialog box.
I also tried the "-d" (debug) version, but nothing happens.
I would be desiderable that a version with debug/log information is provided.

Thanks in advance for your help
Mariano

**Comment by Jojo-Schmitz** [comment]
Hmm, 972dbe2 is a 3 weeks old build, still the same with a latest?
Or: have you been runinng an earlier one successfull and if so which?

**Comment by marianobelaunde** [comment]
Just tested in windows 11 with version of today .... and the musescore GUI opens as expected ! 
By the way, I was also able to "save online" a score without facing the problem I currently have when running MS 3.6.
That's great !

**Comment by Jojo-Schmitz** [comment]
No idea wha the older version didn't run, but won't invest any time in finding out, as the latest version does run.

And yes, that save-online bug doesn't happen with 3.7.
