### ISSUE TITLE
Issue/Confirmation: External SMuFL Fonts loading during save sometimes crashes program in peculiar state. 

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#633]
@Jojo-Schmitz have you encountered a crash when saving a score when using externally loaded fonts? It happens to me on occasion when I'm testing some code changes every now and again, and I think I've found the cause. It cracks out on accessing members of a TextCursor. 

```cpp
void ScoreFont::draw(SymId id, QPainter* painter, const QSizeF& mag, const QPointF& pos, qreal worldScale) const
```
In that function, there's an attempt to "addApplicationFont" if the font is null
```diff
+ if (-1 == QFontDatabase::addApplicationFont(s)) {
```
```cpp
if (MScore::pdfPrinting) {
     if (font == 0) {
           QString s(_fontPath+_filename);
           if (-1 == QFontDatabase::addApplicationFont(s)) {
                 qDebug("Mscore: fatal error: cannot load internal font <%s>", qPrintable(s));
                 return;
                 }
```

instead of loading these external fonts into the FontDatabase during app initialization, like in MScore::init(). Apparently that's mostly fine (but seems a shoddy coding practice generally speaking), but on occasion something happens where there's a TextCursor existing and it triggers
```cpp
TextTools::fontChanged()
```
and that checks if a cursor exists. Unfortunately it *does* exist when it seems it shouldn't, and that then continues on 
with:

```cpp
void TextCursor::setFormat(FormatId id, QVariant val)
      {
      changeSelectionFormat(id, val);
      format()->setFormat(id, val);
      text()->setTextInvalid();
      }
```

and that invokes ```changeSelectionFormat``` 

```cpp
void TextCursor::changeSelectionFormat(FormatId id, QVariant val)
      {
      if (!hasSelection())
            return;
      int r1 = selectLine();
      int r2 = row();
      int c1 = selectColumn();
      int c2 = column();
      sort(r1, c1, r2, c2);
```
and the next line is:
```diff
+      int rows = _text->rows();
```

Ahh! `_text->rows()`, but there's no `_text` that has been "prepared" properly, so calling rows() is totally  undefined or inaccessible, and qt library somewhere down the line screws up when accessing the iterator of the container or something of the sort...

**Comment by Jojo-Schmitz** [comment]
I've not knowingly come accross that problem yet

**Comment by worldwideweary** [comment]
While I'm up...

**Comment by Jojo-Schmitz** [comment]
Ah, that is about the 3.7 feature to load and use external SMuFL fonts, not about some non-builtin text fonts, correct?

**Comment by worldwideweary** [comment]
Yeah, it's the external score fonts SMuFL fonts that get loaded but they don't get actually added to Qt's font application system until the attempt at drawing a Symbol occurs.... this changes that to occur at the initialize stage and also hopefully when the external font directory is changed

**Comment by Jojo-Schmitz** [comment]
Reverting #635, because it causes the ussue from described in https://musescore.org/en/node/368828

**Comment by worldwideweary** [comment]
Hrm. I wonder if I can get the cursor to be disabled/nullptr when it loads and then reload it afterwards so that I don't get that crash on occasion that I mentioned

**Comment by worldwideweary** [comment]
Oh man, I think I may have found a culprit that would have fixed the PR... the code originalyl doesn't even look like it's adding the internal score fonts into the application. I thought it was *was* and was just adding the "external user" score fonts... but it looks like MS needs the internal fonts also loaded in!
