### ISSUE TITLE
Minor issue: Horizontal frame updating width via mouse-dragging doesn't register as undo-able

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#634]
Not a biggie, but figured would register it here. Video from 3.6.2 showing undo not working because no "change state" after dragging horizontal frame. Same for 3.7...

[horizontal-undonope.webm](https://github.com/user-attachments/assets/4c645f8e-09ec-4232-8db8-335028139498)

It *does* work if the width is changed via inspector

P.S. Issue doesn't exist in MSS4.x

**Comment by worldwideweary** [comment]
Investigating further: VBox calls the base Element class on editData.element->endEditDrag(editData); 
whereas H:Box gets its own "special" endEditDrag overload. Why should Vbox not be special but Hbox is? I bet the overload isn't really special and is the culprit

**Comment by Jojo-Schmitz** [comment]
Guess that's why there is no `HBox::endEditDrag()` in Mu4?

**Comment by worldwideweary** [comment]
Probably. Just checked and seems to be fine after removing endEditDrag declaration and definition:

[hframe.webm](https://github.com/user-attachments/assets/d3ff5c44-226e-4f55-a7e2-863359486573)

**Comment by Jojo-Schmitz** [comment]
Are you going to PR it or should I?

**Comment by worldwideweary** [comment]
Might as well PR

**Comment by worldwideweary** [comment]
I got it
