### ISSUE TITLE
Export and Print produce squares in place of note heads

### ISSUE THREAD

**Issue by BanjoJake** [Jojo-Schmitz/MuseScore#642]
Exported from the attached mscz and the got the attached PDF.
observed on Windows 10 in MuseScore (64-bit): 3.7.0.10830939156, [10d1b80](https://github.com/Jojo-Schmitz/MuseScore/commit/10d1b80)
Works correctly in version (64-bit): 3.7.0.10790641907, revision: [1f21da2](https://github.com/Jojo-Schmitz/MuseScore/commit/1f21da2)

[Export Bug (v108).zip](https://github.com/user-attachments/files/17012146/Export.Bug.v108.zip)

**Comment by Jojo-Schmitz** [comment]
Resolved by reverting78c2a4a
