### ISSUE TITLE
Should the crescendo-diminuendo-playback plugin work in 3.7?

### ISSUE THREAD

**Issue by mkj42** [Jojo-Schmitz/MuseScore#652]
On 3.7, I cannot get the crescendo-diminuendo-playback plugin to work.
https://github.com/Jojo-Schmitz/crescendo-diminuendo-playback

I put the .js and .qml files in the plugins subdirectory, but it doesn't even show up in the list of plugins available.
I notice the date is from 2014, and I wonder what all might have changed and if that's the problem, or if I am doing something wrong.

I have a score with all user type velocity, and I would like to edit in some cresc/dim.
It is currently dynamics free, and I would like to keep it that way for now.
Doing it one at a time in the piano roll editor is an option, but very tedious.

Thanks

**Comment by Jojo-Schmitz** [comment]
That plugin is for MuseScore 1.x  and 2.x dnd for those only, it had nevver been ported to 3.x or 4.x, as there it isn't needed anymore:
In 3.x you can change the hairpins's dynamic change in its Inspector
