### ISSUE TITLE
3.6 and 3.7 react different to the following score (copyright)

### ISSUE THREAD

**Issue by ErlingIv** [Jojo-Schmitz/MuseScore#668]
[Test.zip](https://github.com/user-attachments/files/17235137/Test.zip)

**Comment by Jojo-Schmitz** [comment]
3.7 by default uses `$C`, copyright on 1st page only, just like Mu4 does. 3.6 uses `$:copyright:`, copyright an all pages.
This is a deliberate change. If you want 3.7 to not change it, use `$c` in 3.6

**Comment by ErlingIv** [comment]
Ok, no problem. But the "philosophy" as I read this is then : 3.7 "mimic" version 4 not 3.6.

**Comment by Jojo-Schmitz** [comment]
Only where I believe it to make sense ;-)
