### ISSUE TITLE
Save online not working for Linux version: blank window displayed and nothing gets uploaded

### ISSUE THREAD

**Issue by marianobelaunde** [Jojo-Schmitz/MuseScore#682]
The linux version is not able to "save online" scores.
I have just tried with the very last version ...
MuseScoreNightly-202410230435-3.x-f391d7b-x86_64.AppImage
And always the same problem ... a white popup window displaying. 
Also, no specific errors displayed in the terminal ...
I'm attaching the window capture and the terminal capture ...
Maybe someone already find a way to make it work ?
Is there any possibility to display more verbose log traces in the terminal ?
Note: the "save online" on windows 11 version happens to work one day, but actually it does not work anymore.
Thanks in advance for any help.

![musescore37linux-launch](https://github.com/user-attachments/assets/e43d784d-bf02-4ac1-b847-c75fda89d9a0)
![Musescore-SaveOnlineError](https://github.com/user-attachments/assets/5d959cf4-6fe5-43f6-9906-8df1969e2a16)

**Comment by Jojo-Schmitz** [comment]
It is saving online though, only all the modifications to the online information need to be done directly on musescore.com

**Comment by Jojo-Schmitz** [comment]
And I'm pretty sure MuseScore itself is innocent here, it is the backend that is acting up, the official 3.6.2 has the same issue

**Comment by marianobelaunde** [comment]
>>> the online information need to be done directly on musescore.com

That would be great ! Unfortunatly does not seems to be the case. If I connect to musescore.com and I visit my posted scores, all what I can do is to click in the button "Add the missing information", and after that I got a "the suggestion has been successfully sent" which does not do the job at all. That's a pity ! If you know of a hidden link that exists in musescore.com that allow an author to really edit the score description of a previously posted  score, that would really solve the problem.

**Comment by marianobelaunde** [comment]
>>> it is the backend that is acting up, the official 3.6.2 has the same issue

That's true. Some change was done in the musescore.com backend that made Musescore 3.6.2 not work proprely. Never mind, I was hoping Musescore Evolution to find a solution to this issue... I guess this should be possible since Musescore 4.2 has no problem with the "Export online" feature. Maybe the solution will soon arrive with a coming version of Musescore Evolution ?

**Comment by Jojo-Schmitz** [comment]
As it is a problem with the musescore.com backend, there's nothing any code change in the frontend aka MuseScore 3.x could do anything about

**Comment by Jojo-Schmitz** [comment]
And you can update a score's settings on musescore.com under the score's ... menu

**Comment by marianobelaunde** [comment]
> And you can update a score's settings on musescore.com under the score's ... menu

I would be very happy to do that, but I did'nt see any item menu in the score menu that would make that possible.  Please, if you think this is possible, be precise with some screen captures. 

I tried from my side, and, as I told, what I find does not do the job. We do not access a real editing form, just a mean to send suggestions. See the two screen captures below ...

![musescore-filling-missing-data](https://github.com/user-attachments/assets/c8deac46-2895-425d-b644-4580362355d5)
![musescore-thanks-for your-suggestion](https://github.com/user-attachments/assets/3409eaba-231a-4df2-9062-65cdca144cf1)

**Comment by Jojo-Schmitz** [comment]
Feel free to try.
As the changes on the backend are not documented in any form or shape, this won't be easy.

**Comment by marianobelaunde** [comment]
> The screens you show are the wrong ones. Open the score on musescore.com and in the upper right corner use the ... menu

Thanks for the advice ! After some navigation I finally I found the correct update screen in musescore.com (click on "My scores", then click on Pencil icon) ... That's great.
That makes for me less important the resolution of the "save online" problem. 

Notice however that the initial publication after clicking on "save online" works with Windows version, but it does not seems to work with any Linux version. I tried with different distributions, Ubuntu and Debian, and nothing happened behind the scenes of the blank screen.

**Comment by Jojo-Schmitz** [comment]
Hmm, that's bad. No idea why though

**Comment by zorba77** [comment]
I can confirm this bug under linux

**Comment by gadodar** [comment]
Hi, I confirm the same problem under linux mint 22 and musescore 3.6.2 and 3.7.
I tried to load the scores from the site, but it does not load the suondfont libraries and the changes made with the midi editor that I am particularly interested in.
On musescore 4.4.3 it works, but it does not load the midi editor changes.

**Comment by Jojo-Schmitz** [comment]
If 3.6.2 doesn't save online, it won't be a regression.
But don't get fooled by the blank screen, it does save regardless, check directly on musescore.com. and this is a flaw in the site and the site only.

**Comment by Jojo-Schmitz** [comment]
And I don't understand what you mean reg. Sound and MIDI

**Comment by zorba77** [comment]
I tried now, it show blank screen but don't save online the score (under Linux, I don't know with Windows/MacOs)

**Comment by Jojo-Schmitz** [comment]
3.6.2?

**Comment by zorba77** [comment]
no, version 3.6.2 doesn't save online either...  and shows the same blank screen

**Comment by Jojo-Schmitz** [comment]
Then it isn't a regression. And something seriously amiss on musescore.com, please report it there

**Comment by Jojo-Schmitz** [comment]
And actually not a bug to fix here

**Comment by zorba77** [comment]
I tried, but I didn't find a mail to write to. There's only a chat bot

**Comment by Jojo-Schmitz** [comment]
support@musescore.com
