### ISSUE TITLE
Bass clef changes to treble clef on deleting first measure

### ISSUE THREAD

**Issue by yonah-ag** [Jojo-Schmitz/MuseScore#686]
Follow the steps shown in the image with the linked score and you will see that the bass clef magically turns into a treble clef.

![BassToTreble](https://github.com/user-attachments/assets/89b70e21-2630-48c9-a6f1-ce9713a95255)

Score: https://musescore.com/user/28842914/scores/21599197

Sorry but I don't have access to 3.6.2 at present so I can't tell whether this is a regression.

**Comment by Jojo-Schmitz** [comment]
I can't reproduce, not with a new score created from the grand staff template, please attach a sample score

**Comment by Jojo-Schmitz** [comment]
Not a regression, 3.6.2 behaves the same. 4.4.3 and latest master too

**Comment by Jojo-Schmitz** [comment]
And not a bug either:
![image](https://github.com/user-attachments/assets/bb2f4ee5-335c-434b-a4aa-5423e0c9b5e4)
The score apparently hasn't been created from the grand staff template (with that I can't reproduce), but probably by adding a 2nd and 3rd staff to the treble clef, then removing the 2nd staff

Another test/indication: just select the bass clef and press Del

**Comment by yonah-ag** [comment]
I was sent the score by another user in relation to:
https://musescore.org/en/node/371009
so I don't know the origins of the score but it doesn't seem right that a clef should change like this no matter what the score's origin. Is there a way to fix the score so that it behaves better?

**Comment by yonah-ag** [comment]
Note: As a TAB only user I really don't know how linked treble/bass staves should work so my comments may miss the mark.

**Comment by Jojo-Schmitz** [comment]
You'd need to add
```xml
        <defaultClef>F</defaultClef>
```
to the 2nd staff

**Comment by yonah-ag** [comment]
Yuk! The score setup is faulty therefore, as you said: "no bug".
Case closed.

**Comment by knoike** [comment]
I could reproduced this.

Preparation:
Change 2nd staff manually from F clef to B clef.

Select 1st measure and delete -> Clef changed.
Select 2nd measure and delete -> Clef not changed.

It seems the manually entered clef is the content of 1st measure, not staff/part property.
This may "by design", but it seems like strange behavior to me.
@yonah-ag It may good that you request a feature improvement(an feature changes) about this.

**Comment by Jojo-Schmitz** [comment]
If you delete a clef (either directly or along with the measure), it falls back to the previous clef, for the 1st meausure to its default clef, if there isn't any it falls back to treble clef
This is by design and unlikely to change.
If it gets changed for Mu4, I'll consider backporting though ;-)
