### ISSUE TITLE
Option to disable new score wizard

### ISSUE THREAD

**Issue by coding-moding** [Jojo-Schmitz/MuseScore#690]
It would be very convenient to disable the thing that configure parameters that can always be accessed later. You just start composing on default template.

**Comment by Jojo-Schmitz** [comment]
I guess I'd need more explanations on how exactly you'd see this working and why it'd be usefull
Also better request it for upstream too

**Comment by coding-moding** [comment]
"Start with score :/data/My_First_Score.mscx" is triggered once the program starts. I'm saying about ctrl+N that calls the wizard. As you can see they are different things.
I assume it's generally usefull not to do unnecessary things.

You mean MS4? But I don't use it.

**Comment by Jojo-Schmitz** [comment]
Yes, I meant Mu4.
Doing coding for saving just a few clicks for this special case is not worth the effort IMHO.

**Comment by knoike** [comment]
1.
Make the template score you want, and save as .mscz file.

2.
Set the .mscz file to "Start with score [(here)]" 

From the next startup, you just start composing on the template made by you.

Is this something different you want?
I talking about Mu3.

**Comment by Jojo-Schmitz** [comment]
(s)he wants this to happen (also?) when creating a new score via Ctrl+N (or File > New)

**Comment by knoike** [comment]
Ah, I see... .
I don't know if that customization for "new score wizard" would be useful... .
If it were me, instead of using Ctrl+N, I would double-click the template .mscz file to get started.

**Comment by Jojo-Schmitz** [comment]
Indeed another easy way to do it

**Comment by coding-moding** [comment]
Thanks for the alternative way of creating blank sheet. I will use it. But I can point out that it not intuitive way of creating new sheet music. In almost any editor (text or audio) you just press ctrl+n and just start working. You not forced to use some wizards. And wizards can have "dont show wizard next time" button on their dialogs.
I don't think there is much coding. I can make PR for the feature myself.

**Comment by knoike** [comment]
> But I can point out that it not intuitive way of creating new sheet music.

Yes, I agree about this.


> I can make PR for the feature myself.

Good!


> And wizards can have "dont show wizard next time" button on their dialogs.

I think there needs to be a way to either clear this setting or run wizard in case user want to use it again.

**Comment by Jojo-Schmitz** [comment]
Ok, I will check a PR and consider merging it.

**Comment by coding-moding** [comment]
Added the PR
https://github.com/Jojo-Schmitz/MuseScore/pull/700

**Comment by knoike** [comment]
I have added a brief explanation of this new feature to the Wiki.
https://github.com/Jojo-Schmitz/MuseScore/wiki/Musescore-3-Evolution,-Features#option-to-disable-new-score-wizard

**Comment by Jojo-Schmitz** [comment]
Thanks
