### ISSUE TITLE
My Mac says that the app is damaged

### ISSUE THREAD

**Issue by Dmarcus123** [Jojo-Schmitz/MuseScore#696]
I downloaded it from the Artifacts block at the bottom of https://github.com/Jojo-Schmitz/MuseScore/actions/runs/11850153140, opened the download, dragged it to the Apps icon in install screen, waited for it to finish downloading, and tried to open it via double-click from finders (in other words, standard standard standard.

<img width="316" alt="image" src="https://github.com/user-attachments/assets/21383d40-54a7-4754-ba5a-021e36c22984">

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#macos

**Comment by Dmarcus123** [comment]
I have tries control + click, command + click, control+ [right click]Open, ccommand + [right click]Open. I got the same message each time.  

I will try tomorrow with tonight's build.

**Comment by Dmarcus123** [comment]
The screen shot in https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#macos does not show the _file is damaged_ messagec that I am seeing. According to Google translate, it says _MuseScore 4.0.0.3255818193 Devel cannot be opened because the developer cannot be verified_", a very different problem.

**Comment by knoike** [comment]
Have you try to run xattr -cr ?
`xattr -cr /path/to/MuseScore.app`

see https://github.com/Jojo-Schmitz/MuseScore/issues/118

**Comment by Dmarcus123** [comment]
From your recent comment, should I assume you replicated the error that I
saw and have not been able to fix it?

Dave (he / him)

**Comment by knoike** [comment]
This is a well-known workaround to that problem.

**Comment by Jojo-Schmitz** [comment]
It is something that I'd have to mention in the wiki.
The problem of the Mac builds not being notarized comes on top I'm affraid

**Comment by Dmarcus123** [comment]
This problem has been fixed via xattr -c 

thank you
