### ISSUE TITLE
Possible issue with Leland Text

### ISSUE THREAD

**Issue by dragonwithafez** [Jojo-Schmitz/MuseScore#701]
Not sure if this is a bug or an intentional change. When I open a 3.6.2 score in 3.7, the note glyph in tempo markings renders noticeably smaller than it did in 3.6.2.

Compare in 3.6.2:
![image](https://github.com/user-attachments/assets/5b0a48c3-d89f-404d-a2f2-649dd580c664)

Vs how it is in 3.7:
![image](https://github.com/user-attachments/assets/e34cce15-fe50-4ec0-9973-f39ed4fd5662)

I downloaded the old version of Leland and Leland Text included in 3.6.2 and tried using that instead, which did fix the quarter note sizing but caused issues with dynamic markings.

If this intended then sorry for the bother!

**Comment by Jojo-Schmitz** [comment]
3.7 does use a newer version of the Leland font, and that is indeed intentional
