### ISSUE TITLE
Master Palette crashes without stock instruments.xml

### ISSUE THREAD

**Issue by ivan-lt** [Jojo-Schmitz/MuseScore#733]
If in Preferences->Score you delete the reference to :/data/instruments.xml, restart the program and try to invoke Master Palette (Shift-F9 by default), the program crashes.

I know instruments.xml explicitly says:
> don't remove this 'instrument', it is used in ...mscore/noteGroups.cpp to generate the time sig dialog of the master palette

so this behavior probably can't be classified as a bug (more like failure to follow instructions on the user's part), but maybe this situation can be handled more gracefully?

**Comment by Jojo-Schmitz** [comment]
a) does 3.6.2 behave the same (if not, this would be a regression)
b) what does MuseScore 4 do in that case? There you can only delete C:/Program Files/MuseScore 4/instruments/orders.xml though.. But iIf it crashes too, please report there

**Comment by Jojo-Schmitz** [comment]
Only thing I believe 3.7 could do is to refuse to open the time signature dialog (separate or as part of the master palette) and spit out an error dialog

**Comment by Jojo-Schmitz** [comment]
Actually it does die of a failed assertion, but only in debunbg builds gives an error message on the console
```cpp
            qFatal("Did not find instrument <%s>", qPrintable(instrument));
```

```
Debug: palette <.../AppData/Local/MuseScore/MuseScore3/timesigs.mpal> not found (...\mscore\palette.cpp:1456, bool Ms::Palette::read(const QString&))
Fatal: Did not find instrument <voice> (...\libmscore\mcursor.cpp:160, void Ms::MCursor::addPart(const QString&))
```

**Comment by Jojo-Schmitz** [comment]
Seems the crash can get avoided

**Comment by ivan-lt** [comment]
Thank you for your prompt reaction!  I'm working in 3.7 with my own instrument definitions so if the problem persists I'll report.  Can't verify on MS4 because I'm still on Windows 7.  (And I wouldn't use it anyway since the UI is so convoluted and for a host of other reasons.)
