### ISSUE TITLE
3.x (3.7) Loss of images

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#95]
### Issue type

File corruption

### Bug description

Didn't know how to go about sending a message on here to you, so figured an issue makes sense. I'm wanting to see if you can verify this situation with 3.x (3.7):

1) Make new score
2) Do a screenshot or something to clipboard and paste it into a vertical frame for instance
3) Save

4) Close and reopen
> Result: image exists

5) Now make some changes and use save function CTRL+S
6) Close and re-open
> Result: image does not exist! appears with the grey-x like:
> ![Screenshot_2023-04-12_13-00-32](https://user-images.githubusercontent.com/7139517/231571293-3b4cc850-0b7e-4685-b842-faa01513943b.png)

This is a big problemo... still using 3.x due to having too many niceties and customizations that 4.x doesn't come close to for now, and if you can verify this, maybe we can hunt it down.

### Steps to reproduce

.

### MuseScore Version

.

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

.

### Additional context

.

**Comment by Jojo-Schmitz** [comment]
I wonder whether setting `_used` to `true` in the constructors would already fix it. After all those are called when creating/adding/reading an image.

**Comment by Jojo-Schmitz** [comment]
Closed via #96

**Comment by worldwideweary** [comment]
Cool,
The loss of images "sporadically" was enervating.
And yes, seems better to default into true rather than revert.
