### ISSUE TITLE
Crescendo lines overlap + Chord text frame

### ISSUE THREAD

**Issue by worldwideweary** [Jojo-Schmitz/MuseScore#98]
### Issue type

Other type of issue

### Bug description

I'm being lazy and not sending PR requests... but  real quick I'll msg here about: 

Crescendo hairpins at the starting point where the lines meet look slightly bad in 3.x sometimes. MS4 doesn't seem to have this problem. It seems to do with the cap style, and can be fixed adding the setCapStyle call within when if (twoLines):

> void TextLineBaseSegment::draw(QPainter* painter) const

@ the line having:

> if (twoLines) {

add the following:

>    pen.setCapStyle(Qt::FlatCap);

I think there's also a mitre setting that could make it even better but i didn't experiment with that.

Another little problem is that frames don't update the bounding boxes of a chord symbol. This is a big corner case since most people probably don't use frames on chord symbols, but I was doing some inverted color scheme for some negative harmony stuff and found the problem that way. It draws ok, but you can notice on occasion a screw up of a frame because the bbox is reset to be bounded to the chord letters and not take into account a frame and its margins.
You can test the veracity by turning on bounding boxes of a chord symbol when there's a frame existing on it.

To fix this, i provide a screenshot of the code difference from git:

![frameChordFix](https://user-images.githubusercontent.com/7139517/232265165-7444ca9d-2255-441d-91c5-a3c6d35c1503.png)

You see, the calculateBoundingRect() function returns a point and is passed as an argument into setPos(), but that ends up overriding  the results of the previous layout1() function, which is where the frame is taken into account. Making the above changes will fix it. Have a nice day!

 

### Steps to reproduce

.

### MuseScore Version

3.x

### Regression

I don't know

### Operating system

.

### Additional context

.

**Comment by Jojo-Schmitz** [comment]
I guess you mean this?
![image](https://user-images.githubusercontent.com/1786669/232287342-67ec9a31-2377-4204-b43f-19742f03b0ee.png)

**Comment by Jojo-Schmitz** [comment]
Ah, there's also `pen.setJoinStyle(Qt::`RoundJoin);` (supüposed to be) looking like the above RoundCap on the joining end only. Then there's `MiterJoin` and `BevelJoin` (the latter being the default). See https://doc.qt.io/qt-5/qpen.html#join-style
Only neither seems to work here, as both lines are drawn independant of one another, so Qt doesn't know that they are touching one another. So this isn't an option.

**Comment by Jojo-Schmitz** [comment]
The 2nd issue is the same in 4.0.2 and slighly different but similar in current master

**Comment by Jojo-Schmitz** [comment]
Diff between 3.x and 4.x in regards to the harpins:
3.x uses `QPen solidPen(color, textlineLineWidth, Qt::SolidLine);` while 4.x has `const Pen solidPen(color, lineWidth, PenStyle::SolidLine, PenCapStyle::FlatCap, PenJoinStyle::MiterJoin);`, so a `FlatCap` by default (and a `MiterJoin`, which doesn't have any effect here).

**Comment by Jojo-Schmitz** [comment]
Resolved via #99

**Comment by worldwideweary** [comment]
Yes the screenshots are what I experienced. Would've sent you some of my own, but didn't have previous build to show before/after. Good point about the round join: I think it looks nicer that way too.

We can change the code to join these damned lines, and in doing so i'm not so sure just a regular MitreJoin isn't the way to go

Result gives: (using MitreJoin)

https://user-images.githubusercontent.com/7139517/232324389-dc63e322-f8bb-4fc2-a2b1-50cdbdc4f0d0.mp4

and with the rounded type:

https://user-images.githubusercontent.com/7139517/232326404-324b162b-8ba1-4189-b94d-0585411133c1.mp4



At any rate, to get that, here are some diff captures:


![hairpinCode4](https://user-images.githubusercontent.com/7139517/232326217-ce24bd63-3f4c-48a4-9842-c2e6663ccbb6.png)

> void TextLineBaseSegment::draw(QPainter* painter) const 
> @ the same area of if (twoLines) {

![hairpinCode2](https://user-images.githubusercontent.com/7139517/232325773-34b827aa-14df-4216-a4e7-ae6c4e3693fb.png)


![hairpinCode3](https://user-images.githubusercontent.com/7139517/232325781-4d45115a-14a3-4bbf-9eb6-62c48a809fb6.png)

Something similar to this might be worth doing in MS4?

**Comment by Jojo-Schmitz** [comment]
That's be something to ask @oktophonie I guess

**Comment by Jojo-Schmitz** [comment]
Your code doesn't fully work BTW, not for harpins accross a system break, where the lines no longer join, but still do with your code

**Comment by worldwideweary** [comment]
Oh, didn't think about system breaks. I'll look into it.

Also didn't think to mention the brokenPoints thing - it's something else entirely on my local build for centered text-lines like:
![centertext](https://user-images.githubusercontent.com/7139517/232338141-8d954d69-754d-4ff8-a34c-a9474b3cedfe.png)
(where multiple lines have to be drawn in)

**Comment by worldwideweary** [comment]
Ok, test this if you would [works so far over here] (this time i also provide copy/paste lines):
![1](https://user-images.githubusercontent.com/7139517/232339733-f84beb84-32eb-467b-8fab-2105cb101ee5.png)
` if (!joinedHairpin.isEmpty())
                painter->drawPolyline(joinedHairpin);
            else painter->drawLines(&points[0], 2);`
p.s. in the single else statement will do what two original lines did combined.

![2](https://user-images.githubusercontent.com/7139517/232339759-872f382c-37ce-4d25-9587-a2cc62c94f18.png)
` joinedHairpin.clear();
            if (spannerSegmentType() == SpannerSegmentType::BEGIN || spannerSegmentType() == SpannerSegmentType::SINGLE) {
                joinedHairpin << points[1] << points[0] << points[3]; // [top-right, joint, bottom-right]
            }`

**Comment by worldwideweary** [comment]
Test

**Comment by worldwideweary** [comment]
Shoot, still a problem ( the joint of diminish line doesn't round on a system span... i'll fix that real quick and delete this comment )

**Comment by Jojo-Schmitz** [comment]
Still fails for cross-system-break diminuendos

**Comment by worldwideweary** [comment]
Oh, I see. Didn't take into account the actual default desired behavior properly. But you're right, also not beginning for the decresc will take care of that. Looks like your  #100 does it. I won't mess with it for now, but it would be cool if MU4 gave the user an option to have mitre joining or round joining, but maybe that's too much control for the average user. Thanks for testing/fixing the last bit of code btw.

**Comment by Jojo-Schmitz** [comment]
> ... and in doing so i'm not so sure just a regular MitreJoin isn't the way to go...

This sentence is confusing me a lot, that double negate.

**Comment by worldwideweary** [comment]
> This sentence is confusing me a lot, that double negate.

In other, more positive words: a regular Miter joint might be the proper choice - a user-option would be nice.

**Comment by Jojo-Schmitz** [comment]
As mentioned in https://github.com/musescore/MuseScore/pull/17269 `BevelJoin` might be a viable option too.

**Comment by Jojo-Schmitz** [comment]
I'll test and probably add this to #100, probably change to `BevelJoin` and revert to `SquareCaps` (the latter seems not needed for polygons)
